### ISSUE TITLE
Saving completed dependencies makes them top-level

### ISSUE THREAD

**Issue by luisggpina** [tbabej/taskwiki#100]
I have this project:

```
== Tasks | project:myproject ==
    * [ ] A
        * [X] B
        * [X] C
```

After saving:

```
== Tasks | project:myproject ==
    * [ ] A
    * [X] B
    * [X] C
```

The dependent tasks are now top level.

Even if I manually set them dependencies in A, saving this file will make B and C toplevel.  This sucks because I'm always losing precious information about the structure of my projects as I complete tasks.

**Comment by tbabej** [comment]
Thanks for reporting.

I fixed this in master (it was quite a hidden culprit) and wrote a test to cover this issue.

**Comment by luisggpina** [comment]
Thanks!  I should have submitted a PR, I fixed it in the same way on my machine but the code looked so "meant to be there" that I thought it was a feature and not a bug.  I'm actively using this project to manage my tasks, so I'll do that on the eventual next issue I open.

**Comment by tbabej** [comment]
Well, to be honest, I *think* it was meant to be there - probably some older versions of TW / tasklib did not support setting completed tasks as dependencies. I do not remember anymore.

However, tests pass on all supported versions (2.4.0+), so all is good.
