### ISSUE TITLE
how do you end/clear a viewport?

### ISSUE THREAD

**Issue by hpfast** [tbabej/taskwiki#104]
I have a wiki page with a viewport project:test and some tasks listed under it.

Further down the page I have totally unrelated tasks. But it seems they are still in scope of the viewport, because they get automatically get the project 'test' and get added to the viewport's tasklist (now appearing in two places on the page).

I found the -VISIBLE modifier which prevents tags shown elsewhere from being displayed in the viewport, but they still get the test project added in taskwarrior.

I can't find anything about preventing this, but it seems like it would be desirable to have unrelated tasks in the same file. Or is there something I'm missing or am I not understanding the intended use-case?

**Comment by tbabej** [comment]
This seems to be correct. It's been quite some time, so I do not remember my motivation, but I think I created this behavior on purpose.

Currently the rule's as follows: If a task finds any viewport above it, the defaults will be sourced from it and the search for any additional viewports abandoned.

However, it's something that we can discuss. Maybe any vimwiki header could terminate this?

**Comment by NullInfinity** [comment]
I think a header terminating the viewport would be more intuitive (indeed that's what I assumed did happen without having looked into it). What if the viewport continues until another header of the same depth/size as the one in which it were defined? So it would be like:
```
= Viewport 1 | <filter> =
(viewport 1)

== Sub heading ==
(still viewport 1)

= Viewport 2 | <another filter> =
(now viewport 2)
```

Also, to confirm, if I have multiple viewports in a file, will a task always take defaults from the next viewport definition found above it?

**Comment by tbabej** [comment]
Yes, task looks for the closest viewport above it when determining its defaults.

Your proposed solution would be probably the most sensible one, I just didn't get around to fixing this one yet. The other, simpler option, would be for any heading to terminate a viewport. Any of those, however, would be an improvement to current situation.

**Comment by tbabej** [comment]
Indeed, I went with the simpler solution for now. Fixed in master.

**Comment by NullInfinity** [comment]
Great, thanks for the quick fix. This is an awesome plugin by the way -- keep up the good work!

**Comment by tbabej** [comment]
Yeah, I just figured we spent more time talking about this than it takes to fix it :) Thanks.
