### ISSUE TITLE
Entering wiki page stops working and shows task properties

### ISSUE THREAD

**Issue by cayco** [tbabej/taskwiki#105]
I have a index.wiki page that has several entries. On of the entry there is a another wiki page which contains tasks and notes. While I enter (return key) on some of pages it works but there are some pages that work only if I exit VIM and enter to them as first page. If I enter to some other page and them to this very "special" page I get task properties window on the bottom and I cannot access the page. Only way is to restart VIM.

It's difficult to describe. Please see the gif how inconsistly it works in the attached gif file. I was able to access Wspin page but while I went to Produktywnosc page, went back and tried to enter to Wspin again it didn't work. It showed some task's properties.

I am on macOs Sierra, brew i up to date.
![taskwiki](https://cloud.githubusercontent.com/assets/7169483/19469572/2a19a35c-951c-11e6-8444-af69acb9f506.gif)

**Comment by tbabej** [comment]
I don't use the linking capabilities within one wiki usually, so this might be the reason I did not come across this so far, but here's my guess:

When jumping across the wiki pages, the cache is not properly cleared, and when you try to access a link which is on the line number where the cache thinks a task is located, an info window will pop up.

This happens since Taskwiki overrides <CR> binding, and passes it over to vimwiki only if no taskwiki object is defined on that line (i.e no viewport / task info to show).

**Comment by hammerheadlemon** [comment]
I'm seeing this too. Is there an easy way to clear the cache?

**Comment by tbabej** [comment]
Maybe this one liner could help. Can you guys verify?

```viml
git diff ftplugin/vimwiki.vim
diff --git a/ftplugin/vimwiki.vim b/ftplugin/vimwiki.vim
index 1df1b93..f0e91ad 100644
--- a/ftplugin/vimwiki.vim
+++ b/ftplugin/vimwiki.vim
@@ -36,6 +36,8 @@ augroup taskwiki
       execute "autocmd BufWinEnter *.".expand('%:e')." silent! loadview"
       execute "autocmd BufWinEnter *.".expand('%:e')." silent! doautocmd SessionLoadPost *.".expand('%:e')
     endif
+    execute "autocmd BufEnter *.".expand('%:e')." :py cache.reset()"
 augroup END
 
 " Global update commands
```

**Comment by hammerheadlemon** [comment]
Is this in `taskwiki` or `vimwiki` repo? Just figuring how to `git diff` a submodule... (taskwiki and vimwiki in my dotfiles repo)

**Comment by hammerheadlemon** [comment]
There is definitely some strange behaviour happening with my setup. There is the subject of this Issue (possibly an issue with the cache), but I am also unable to retain changes between taskwiki and task. For example, I check off an item in taskwiki as done and the change is immediately updated in the task db, but if I write the file in taskwiki, the item becomes unchecked and it reappears in task. I'm assuming these two issues are related somehow. Not experienced enough with vim plugins to be able to debug very far, and not sure exactly how taskwiki and vimwiki relate to each other. Happy to open a new issue if preferred. Thanks for any help!

**Comment by tbabej** [comment]
I pushed an update that may fix this. Can you please try to reproduce?

**Comment by tbabej** [comment]
I can no longer reproduce this, if you are able to, please reopen.
