### ISSUE TITLE
Taskwiki breaks vimwiki link syntax highlighting

### ISSUE THREAD

**Issue by NullInfinity** [tbabej/taskwiki#106]
Default behaviour in `vimwiki` is that a `[[link]]` shows up as `link`, but the full form appears when the cursor is on it. However, once `taskwiki` is installed, I find that the full form shows up only when the cursor is on the link *and* insert mode is entered.

Reproducible with a minimal vimrc and only these two plugins. Has anyone else experienced this? Is it possible to fix it?

**Comment by tbabej** [comment]
I think this is related to the concealcursor option. Taskwiki automatically sets `concealcursor=nc` locally:
https://github.com/tbabej/taskwiki/blob/master/after/syntax/vimwiki.vim#L46

Changing this to `concealcursor=` should fix the issue for you.

**Comment by NullInfinity** [comment]
Thanks, @tbabej, that fixes it. Is there any particular reason this is set by `taskwiki`, or is it just preference? If so, would you accept a pull request to make it possible to disable this via an option like `taskwiki_concealcursor`?

**Comment by tbabej** [comment]
It was my preference (not setting this makes wave effect if you go down a longer tasklist, as UUIDs appear and disappear). I try to avoid having a turnon/off option for each feature, hence I have to make some preferences / assumptions.

I will certainly accept a pull request.

**Comment by NullInfinity** [comment]
I can see why that 'wave effect' could be annoying. On the other hand when I have links like `[[link|text]]` it can be difficult to use motions etc on them as the link doesn't show up in normal mode. I will make a pull request soon :)
