### ISSUE TITLE
TaskWiki finds task dependencies where there are none

### ISSUE THREAD

**Issue by canaaerus** [tbabej/taskwiki#120]
A task which is indented, can block a less-indented task above it. This should not be possible, when there is another regular list-entry between the two tasks.

For example in the following document:

```
= Section 1 =

* [ ] Test Task 1  #3d74a119

= Section 2 =

* Point 1
    * [ ] Test Task 2  #da564ef1
```

_Task2_ is blocking _Task1_ although they have no actual relation.

**Comment by tbabej** [comment]
Thanks for reporting the bug. Yes, this is an issue with our current detection of parent tasks, we do not terminate the search on lines that invalid. We should probably terminate the search on:

* any less indented list item line
* any non-list item line

**Comment by canaaerus** [comment]
I was just looking at this issue and found the corresponding method `VimwikiTask.find_parent_task` in `vwtask.py:332`.

The simplest solution, I think, would be to terminate the search on anything which is less indented. (Though I do not know how to determine that in the given code context.)

Terminating on correctly indented non-list items is not a good idea, in my opinion, because there may be indented paragraphs which belong to the list. For example
```
* [ ] Test Task 1.
    Some description for task 1.
    * [ ] Subtask of Task 1
```

In certain cases even terminating on something less-indented might be too early. For example a preformated code block, might not be indented
```
* [ ] Test Task 1
     {{{sh
echo 'do something regarding Task 1';
    }}}
    * [ ] Subtask of Task 1
```

In theory this could be detected through the vim syntax groups applied by vimwiki, but I am not sure how hard that would be to implement. Seeing that these cases are rare, the simple solution is probably the best thing to do.

**Comment by tbabej** [comment]
I agree. Would you be up to it, given you already perused the relevant parts of the code?

**Comment by canaaerus** [comment]
This is fixed—great. I will add tests later.
