### ISSUE TITLE
Viewports write broken on Neovim with py3

### ISSUE THREAD

**Issue by BonarBeavis** [tbabej/taskwiki#121]
Hi,

can't get a meaningful error message, it is truncated:

```
File "/usr/local/lib/python3.5/dist-packages/tasklib/backends.py", line 281, in execute_command                                                                         
    raise TaskWarriorException(error_msg)                                                                                                                                 
tasklib.backends.TaskWarriorException: Using alternate .taskrc file /home/someone/.taskrc                                                                                  
Configu
```

Any help?

**Comment by tbabej** [comment]
If `:messages` does not show it, try reproducing the error in regular vim. It does not suffer from this error message cutoff issue (hopefully neovim will fix this soon).

**Comment by BonarBeavis** [comment]
It only happens when a recurring task is defined. Are recurring tasks not supported?

**Comment by tbabej** [comment]
There should be no problems with recurring tasks, they are supported.

**Comment by BonarBeavis** [comment]
I can't install Vim right know. I file a bug against Neovim and reopen, when I have an error message.
