### ISSUE TITLE
TestViewportRecurrentInstanceTaskGeneration does not work

### ISSUE THREAD

**Issue by canaaerus** [tbabej/taskwiki#128]
The `vimoutput` is causing a mismatch:

```
(Pdb) self.read_buffer()
[u'=== Work tasks | +TODAY ===', u'* [ ] daily task (2017-01-27 00:00)  #e262b465']
(Pdb) lines
['=== Work tasks | +TODAY ===', '* [ ] daily task  #169735fe']
```

So the due date is missing and the uuid is different. The latter is probably because one is the recur template and the other is the current instance. No idea how to work around those issues though...

**Comment by tbabej** [comment]
This was pushed by mistake, I removed it. I had some weird problem with the test, and I haven't had the time to look into it yet.
