### ISSUE TITLE
backlinks options

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#13]
(related to #3)

When tasks exist in wikis, there is often benefit in embedding a link in the task data, so that one can easily find the wiki from the task, _however_ there are desirable configuration options. here are a few ideas;

g:taskwiki_backlinks_enabled=1 (or 0=disabled)
g:taskwiki_backlinks_type=annotation (or 'uda: blink')
g:taskwiki_backlinks_prefix='wiki: '  (good for annotation-type, not so good for UDAs)

There are also strong arguments for in-line overrides to the backlinks_enabled config. For example, if I wanted to have a record of my tasking activity in my vimwiki-diary (which I do) and that featured a listing of every task added, completed or due on that day, then that would cause _every_ task to have a link to a diary file, and that would be.. noisy. So, much like the project-default and tag-default inline settings, backlinks  on-and-off settings would be great, like;

%backlinks (at the top of the file, with no other over-ride, would turn on backlinks for the whole file)

task, task, task list

%nobacklinks (turns off backlink behavior for tasks that follow)

task, task, task list

%backlinks (and back on again)

**Comment by linuxcaffe** [comment]
Thinking about this one, global backlinks don't make sense, too much potential noise in the task data, with potential for a task to be presented in several files, in several viewports, and per-viewport isn't much better, so

Perhaps something a :TWWLink command, to be used per-task or on a visually-selected group. 
This command would add an annotation;
<pre>
wiki: ~/path/to/file.wiki 
</pre>
to the selected task(s). 
A task could have N wiki path annotations, but each of them would have to be applied deliberately, using the command.
No other magic required!

**Comment by tbabej** [comment]
A simple command is much easier to live with. I implemented this yesterday, as it's reasonably simple (less than 10 lines). Available via ```:TaskWikiLink``` command.
