### ISSUE TITLE
Failure when using filters with empty properties or negated virtual tags

### ISSUE THREAD

**Issue by callahad** [tbabej/taskwiki#132]
Using the latest versions of taskwiki and tasklib in neovim and Python3. Each of the following filters cause Taskwiki to throw, despite working on the command line:

```
== Tasks that do not have a project | project: ==
== Tasks that are not due | -DUE ==
```

Their positive versions *do* work in Taskwiki:

```
== Tasks that do have a project | project:work ==
== Tasks that are due | +DUE ==
```

The Python backtrace is:

```
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dan/.vim/plugged/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/dan/.vim/plugged/taskwiki/taskwiki/main.py", line 57, in update_to_tw
    c.evaluate_viewports()
  File "/home/dan/.vim/plugged/taskwiki/taskwiki/cache.py", line 216, in evaluate_viewports
    port.sync_with_taskwarrior()
  File "/home/dan/.vim/plugged/taskwiki/taskwiki/viewport.py", line 376, in sync_with_taskwarrior
    sort.TaskSorter(self.cache, self.tasks, self.sort).execute()
  File "/home/dan/.vim/plugged/taskwiki/taskwiki/sort.py", line 37, in execute
    child.parent = node
  File "/home/dan/.vim/plugged/taskwiki/taskwiki/sort.py", line 154, in parent
```

**Comment by callahad** [comment]
Amusingly enough, those filters work fine as long as there's at least one positive other term. E.g.:

- `+PENDING project:` works, `-PENDING project:` does not.
- `+PENDING -PROJECT` works, `-PENDING +PROJECT` works, `-PENDING -PROJECT` does not.

**Comment by tbabej** [comment]
Given that `sort.py:154` is raising `"TaskCollectionNode %s cannot have multiple parents"`, I guess the problem is that somewhere in your task database, you have at least three tasks A,B,C where:

* C depends directly on A
* C depends directly on B

taskwiki is unable to cope with such scenario, since it doesn't know how to build the dependency tree. The whole filtering mystery would boil down to fact that filters that do not work actually select tasks A,B,C for which this failure occurs.

I recommend re-trying with a vanilla task database (maybe adding some tasks, but making sure not to break dependency tree hierarchy). Let us know if the issue persists.

**Comment by callahad** [comment]
I don't believe that's the case in my database; as far as I can tell, I only have 11 tasks in my database with dependencies (`task depends.not: list`), each task only has one dependency, and no series of dependencies are cyclic.

...but looking at sort.py, I don't see any other explanation.

Let me try manually scrubbing those dependencies and seeing if that changes anything.

**Comment by callahad** [comment]
Huh. Yep. That solves it. Now to go one-by-one and figure out which dep was breaking things. :(

**Comment by callahad** [comment]
Oh! I was looking at the dependency graph the wrong way. Here's a minimal case that causes this:

```
$ task add Buy batteries
Created task 1.
$ task add Replace batteries in clock depends:1
Created task 2.
$ task add Replace batteries in remote depends:1
Created task 3.
```

...and I see how that would be difficult to represent in TaskWiki. Any suggestions for modeling that scenario?

More generally, it seems like TaskWiki does a good job of representing "Task X is blocked until A/B/C are completed", but doesn't have a way to represent the inverse, where many tasks are waiting on another: "Tasks A/B/C are blocked until Task X is completed"

**Comment by tbabej** [comment]
That's exactly the case. At some point I was thinking of duplicating the task X in the tree, but decided against it, so we're stuck with this error.

The dependency trees are meant to be a mere substitute until proper subtask support comes in taskwarrior (at which point we will display the subtask tree in the taskwiki, and forget about dependencies), but that is still future releases material.

**Comment by callahad** [comment]
Closing this as user error and adjusting my taskwarrior usage accordingly :) Thank you for the quick responses, and for TaskWiki. I can finally make sense of my amorphous blob of a taskwarrior database!
