### ISSUE TITLE
Taskwiki not detecting tasklib in Arch

### ISSUE THREAD

**Issue by jvmCarneiro** [tbabej/taskwiki#133]
It's my first time installing Taskwiki, and it's giving me an error right when I start vimwiki (\ww):
```
"~/vimwiki/index.wiki" 5L, 287C                                                                                       
Error detected while processing /home/jcarneiro/.vim/bundle/taskwiki/ftplugin/vimwiki.vim:
line   31:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jcarneiro/.vim/bundle/taskwiki/taskwiki/main.py", line 15, in <module>
    from taskwiki import cache as cache_module
  File "/home/jcarneiro/.vim/bundle/taskwiki/taskwiki/cache.py", line 5, in <module>
    from taskwiki import viewport
  File "/home/jcarneiro/.vim/bundle/taskwiki/taskwiki/viewport.py", line 6, in <module>
    from taskwiki import vwtask
  File "/home/jcarneiro/.vim/bundle/taskwiki/taskwiki/vwtask.py", line 7, in <module>
    from tasklib import Task
ImportError: No module named tasklib
Error detected while processing BufEnter Auto commands for "*.wiki":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cache' is not defined
Press ENTER or type command to continue
```
The only difference from the instruction in the README is that I had to install vimwiki to ~/.vim/bundle/vimwiki/ in order to pathogen to find it. Pip also installs tasklib successfully, and if I try to run it again it states that all dependencies are already installed. 

Arch Linux names python3 as python and python 2.7 as python2 in its repo, which I believe it's not common among other distros. I've installed everything using python 3 tools, maybe it's something related to that?

**Comment by jvmCarneiro** [comment]
Also, I just tried installing the [python-tasklib AUR package](https://aur.archlinux.org/packages/python-tasklib/) in the hopes it wold have come adapted to Arch, but the error stays exactly the same.

**Comment by tbabej** [comment]
Most likely. Taskwiki prefers python2 over python3 in case both are available. That is, it did until now. I just pushed a commit that reverses this order of preferences (since not only Arch, but also Fedora 25 uses python3 as pip's default python version).

In other words, update taskwiki and your issue should be gone.

**Comment by jvmCarneiro** [comment]
Another error popped up, but it seems to be just a simple syntax mishap:
```
"~/vimwiki/index.wiki" 5L, 287C                                                                                       
Error detected while processing /home/jcarneiro/.vim/plugged/taskwiki/ftplugin/vimwiki.vim:
line    8:
E582: :elseif without :if: elseif has("nvim")
line   11:
E582: :elseif without :if: elseif has("python3") && ! exists("g:taskwiki_use_python2")
line   14:
E582: :elseif without :if: elseif has("python")
line   17:
E581: :else without :if: else
line   18:
Taskwiki requires Vim compiled with the Python support.
Press ENTER or type command to continue
```

Oh, and Arch's vim build actually comes with +python/dyn and +python3/dyn, should them be included in the if?
```
$ vim --version | grep python
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
```

**Comment by tbabej** [comment]
Just fixed the syntax problem.

Yes, a lot of builds come both with python3 and python2  support, but vim is capable only of using one at the same time. You can try that yourself by running a `:py3 print(3)` after a `:py print 2` command.

**Comment by jvmCarneiro** [comment]
Oh, I see. Awesome man, working perfectly now! Thank you.
