### ISSUE TITLE
Marking a task as completed is very slow

### ISSUE THREAD

**Issue by philipsd6** [tbabej/taskwiki#135]
Most actions are slow actually, but in particular, when I mark a task as completed with `\td`, it takes about 9 seconds to mark the task completed and return UI control to me. The same action using the `task` CLI client is quick. 

I'm not sure how to diagnose this -- is there a way to profile this and see where the bottleneck is? I tried `:profile func *` but the logfile didn't contain anything from vimwiki or taskwiki...

**Comment by tbabej** [comment]
Sorry to hear that. Right now there are no built-in profiling capabilities in taskwiki, but you can easily hack something by adding timestamps outputs to the python files. The vim's `profile func *` wouldn't work since nearly all the execution time happens in the python process.

**Comment by tbabej** [comment]
Cannot reproduce at this moment. Please reopen if the issue persists.
