### ISSUE TITLE
bug: ViewPort +tag filter not restricted to tags

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#14]
<pre>
== Test tags | +test ==
</pre>
delivers a list of 62 tasks with "test" in tag, description or annotation, when there are actually only 5 task with "+test' tags.

**Comment by tbabej** [comment]
I cannot reproduce this. Can you run:

    task rc:/ rc.recurrence.confirmation=no rc.confirmation=no rc.dependency.confirmation=no rc.data.location=<task data location> export -- +test

**Comment by linuxcaffe** [comment]
notaproblem! I think I was suffering from a 
<pre>
project: tw
</pre>
elsewhere in the file.
