### ISSUE TITLE
Can't seem to install on OS X || vim 8 || tasklib 1.0 || latest taskwiki

### ISSUE THREAD

**Issue by arooni** [tbabej/taskwiki#140]
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  2 2017 03:55:34)

I installed via plugged.  I can call the :help taskwiki and see the help, but any of the :TaskWiki commands do not seem to be there for me.  

Vim version;
[I]  ~   master   vim --version | ack python
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore

from :PlugUpdate
- vimwiki: Already up-to-date.
- taskwiki: Already up-to-date.

from pip list:
tasklib (1.0.0)

What am I doing wrong ?

**Comment by arooni** [comment]
fixed it!  

You might want to add to the instructions that you need to run :VimwikiDiaryIndex ; or at least have the vimwiki directory setup and running for TaskWiki to work.  Maybe it's obvious to other users but as a new vimwiki user it wasn't obvious to me.

**Comment by tbabej** [comment]
Great to see you got it working! We accept well crafted pull requests any time, even for documentation.

**Comment by jcrben** [comment]
My mistake - with macOS & neovim - was that I had forgotten to install vimwki, but I didn't need a directory set up or anything - just needed to be editing a `*.wiki`file - created a new one as `index.wiki`.

**Comment by kuity** [comment]
In case someone made the same noob mistake as me...my Python did not have neovim library installed so taskwiki wasn't working at all. Can check this with `:Checkhealth`
