### ISSUE TITLE
:TaskWikiEdit results in error in neovim.

### ISSUE THREAD

**Issue by crocket** [tbabej/taskwiki#141]
![2017-05-19_fri_09 37 51](https://cloud.githubusercontent.com/assets/748856/26242201/81ff5532-3cc2-11e7-8225-e7b7366429ac.png)

neovim 0.2.0
https://github.com/tbabej/taskwiki/commit/6bcc93cfe69f699c6cdd3d01b9abd8f9112a0e67
tasklib 1.1.0
https://github.com/vimwiki/vimwiki/commit/8cdc1c15388cc7f4edb827ff15dbc31d592a79af

**Comment by crocket** [comment]
https://bug.tasktools.org/browse/TW-1862 seems to be related to this issue.

**Comment by tbabej** [comment]
It seems that this is a Neovim problem (I can also reproduce with :! nvim somefile from within nvim).

**Comment by crocket** [comment]
Is vim capable of executing `! vim some_file`?

**Comment by tbabej** [comment]
I pushed a fix for this, but I lack the environment to test it right now. Maybe you can verify?

**Comment by crocket** [comment]
Vundle is cool. `:PluginUpdate` installs your latest commit. If I press `\te` on one of tasks, I see

![2017-05-20_sat_14 02 40](https://cloud.githubusercontent.com/assets/748856/26276346/a4e57ce0-3db0-11e7-9cec-3d7b5218b12a.png)

If I press `:q` in the editing buffer, I see

![2017-05-20_sat_14 02 47](https://cloud.githubusercontent.com/assets/748856/26276350/b39c46c4-3db0-11e7-9b2e-8106a7f82cf9.png)

At this point, I have to press `Enter` to get past `[Process exited 0]`.
Although I want to prevent `[Process exited 0]` from making me press `Enter`, I think it works.
