### ISSUE TITLE
I can create tasks via taskwiki; but can't get viewports working

### ISSUE THREAD

**Issue by arooni** [tbabej/taskwiki#142]
I can create tasks but when I try to view tasks in the viewport say

 == Task Warrior Tasks | project:taskwarrior ==

1)  I just see it highlighted in red and no tasks come in below it, even though I have several taskwarrior project tasks.  Why is this?

1.5) Is there any limit to the filters I can write with taskwiki?  For instance in task warrior I can pass the foo argument and it'll find all tasks with foo in the description.  can I assume anything after the | character is something I could add to a command line task search?

2) In addition, how would I create subtasks that stay in the same project?  For instance in the below example two tasks are created but only the parent task has the taskwarrrior project.

* [ ] test of creating a taskwarrior project  parent task project:taskwarrior
  * [ ] subtask

3) Subtask doesn't have project:taskwarrior.  Is there anyway to get this working?  Seems superfluous to have to type it each time.

I feel I'm on the urge of loving this, just need to get these veiwports working and pulling in tasks from taskwarrior.

**Comment by tbabej** [comment]
Subtasks do not inherit the project from the parent (this is something that would have to be implemented in taskwarrior directly, and indeed, there are plans for that). If you define all these tasks under a viewport however, they both get all the default attributes from the viewport.

I can only suspect that you're doing something wrong with your filter - you can see how taskwiki interprets your filter by "inspecting" the viewport with <Enter>.

**Comment by arooni** [comment]
I appreciate your prompt reply.  

I copied your example of == Home tasks | project:Home == ... and I just see red text (I have a few tasks with the Home project.  

Then when hit Enter on enter on either the "Home" or "tasks" they change from red to purple.  Hitting enter again shows an empty list

When trying to edit it again I see:

 == [[Home]] [[tasks]] | project:Home ==


-----------------------------------------------------------------------

Interestingly enough, I just tested on my Ubuntu machine and it pulls in the tasks just fine.  So maybe this is a localized issue on mac with homebrew/python etc?  Do you have os x users who use it just fine?  Are they using python2 or python3 ?

**Comment by arooni** [comment]
It looks like the python version was the key.  My original version of vim was compiled with python 2.x support.  When I removed it, then ran brew cleanup, then brew install vim --without-python --with-python3  ;; then installed tasklib via pip3, everything works great.  So there might be an issue with getting everything linked up under python2, I'd recommend folks try python3 if they're having issues.

Thanks for this awesomeness!  

PS: i assume that once vim wiki is installed; i can use the taskwiki format on any vimwiki page?

**Comment by tbabej** [comment]
Glad to see you got it working. I gather then the issue is resolved?
