### ISSUE TITLE
Insert existing task into text

### ISSUE THREAD

**Issue by MartyLake** [tbabej/taskwiki#149]
Hello,

As I am typing text, I can already create a new task by typing "new line star space [ space ] mytasktext". This will create a new task when the buffer will be saved, and it's content will be synced (#awesome!!!).

However, is it possible to insert an existing task instead of creating a new one ?

Best,

**Comment by tbabej** [comment]
You can use a dummy viewport to generate the tasks matching a filter, and then copy them away from the viewport.

There, unfortunately, is no ':TaskWikiSearch' command, that would take a filter and insert the list of tasks directly where the cursor stands.

**Comment by MartyLake** [comment]
Thanks for your quick answer!

In my case, I only had one task. Would it be possible to insert one task by
giving it's UID for example ?


---
Matthieu TALBOT
neogaldr@gmail.com

+33 629 22 15 70
fr.linkedin.com/in/matthieutalbot
http://www.soundcloud.com/Marty-Lake
http://lifehacker.com/5028808/how-eom-makes-your-email-more-efficient

**Comment by tbabej** [comment]
Well, it is a bit cumbersome, but you can do:

```
This is some text that I am writing, blah.

* [ ] this will be replaced with the correct description #abcdef01 <--- correct uuid in the short form
```

then, **without** saving the file first, run `:TaskWikiBufferLoad`.

**Comment by MartyLake** [comment]
Thanks a lot for all these **ninja** tricks !!!! Best !


---
Matthieu TALBOT
neogaldr@gmail.com

+33 629 22 15 70
fr.linkedin.com/in/matthieutalbot
http://www.soundcloud.com/Marty-Lake
http://lifehacker.com/5028808/how-eom-makes-your-email-more-efficient

**Comment by tbabej** [comment]
Closing for now.
