### ISSUE TITLE
bug: ViewPort status:pending and +PENDING ignored

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#15]
On my box, 'tw proj:tw' yields 20 pending tasks, and 'tw proj:tw all' only shows 27 tasks, but
<pre>
== Taskwarrior tasks | project:tw ==
</pre>
generates a list of 80 tasks! (most of them since deleted)
This ViewPort includes some completed tasks, but neither
<pre>
== Taskwarrior tasks | status:pending project:tw ==
</pre>
nor
<pre>
== Taskwarrior tasks | +PENDING project:tw ==
</pre>
make any difference, still 80 tasks.

**Comment by tbabej** [comment]
I suspect you generated the tasks in the viewport and then just changed the definition, keeping the tasks intact, right?

The viewports did not remove redundant tasks, but the current version should. Please re-test.

**Comment by linuxcaffe** [comment]
works!
