### ISSUE TITLE
Can't install on macOS Sierra, NeoVim

### ISSUE THREAD

**Issue by eprislac** [tbabej/taskwiki#151]
I have my plugin directory set up as `~/.vim/pack/eprislac/start`, and have cloned the plugin src into this `~/.vim/pack/eprislac/start/taskwiki`. 

I am not using a plugin manager, instead using NeoVim's native plugin management.

After cloning the plugin into the proper directory, I run `:UpdateRemotePlugins`, then restart neovim.

All requirements are installed, and VimWiki runs, but no commands for TaskWiki work.

![screen shot 2017-07-06 at 2 52 31 pm](https://user-images.githubusercontent.com/11530791/27930020-c806af04-625a-11e7-85dc-6b20fccf35b6.png)

**Comment by tbabej** [comment]
If you're experiencing no errors, then I would say that taskwiki did not load at all. I am not familiar with the new native plugin management feature, are you sure that you placed the plugin properly?

You can verify if the taskwiki is loaded using the list of loaded script files that is produced by the `:scriptnames` command.

**Comment by tbabej** [comment]
@eprislac Any updates on this?

**Comment by tbabej** [comment]
If anybody has issues on MacOS, feel free to reopen this issue. Closing for now.

**Comment by jcrben** [comment]
Works well for me, but for those who are having issues, run `:CheckHealth` which will tell you if your Python is set up properly. It can be confusing, especially with system, pyenv, and homebrew python mixed together.
