### ISSUE TITLE
Default tags are overwritten, not appended to

### ISSUE THREAD

**Issue by canaaerus** [tbabej/taskwiki#155]
Consider this example:

```
=== Work tasks | +work ===
* [ ] Some hard task -- +hard
```

I would expect that to yield a task with tags `+word +hard`. Currently `VimwikiTask.task.tags` is assigned as a complete `set` instead of being appended to. Thus the default tags are overwritten and the above example creates a task with only one tag `+hard`.

**Comment by tbabej** [comment]
Thanks, fixed in master, covered by an integration test.
