### ISSUE TITLE
Long viewport filters do not "properly" conceal if they are wrapped onto another line

### ISSUE THREAD

**Issue by SCassidy-UK** [tbabej/taskwiki#157]
If I have a long filter that crosses over to another line due to (soft) wrapping in vim, it displays like this after concealing:
```
== TODO LIST
==
```
Obviously not the end of the world, but it's a bit annoying.

My vimrc just has `set wrap lbr` for wrapping. Is there another vim setting I can change, or a way to fix this?

**Comment by tbabej** [comment]
As you seem to be aware, this is an issue directly in vim. There is no workaround that I know of, other than turning off the wrapping completely.
