### ISSUE TITLE
move ftplugin/vimwiki.vim -> ftplugin/vimwiki/taskwiki.vim

### ISSUE THREAD

**Issue by williamjameshandley** [tbabej/taskwiki#159]
If one is not using a local manager, but wanting to install globally into a single plugins directory (as is the case for arch linux vim packages), then ftplugin/vimwiki.vim conflicts with vimwiki's own ftplugin file.

This problem is easily fixed my moving ftplugin/vimwiki to ftplugin/vimwiki/taskwiki.vim, and changing the line
`let s:plugin_path = escape(expand('<sfile>:p:h:h'), '\')`
to
`let s:plugin_path = escape(expand('<sfile>:p:h:h:h'), '\')`
(i.e. adding an extra `:h`)

**Comment by rustikus** [comment]
I think this also applies if your are using dein as a plugin manager. At least for me it does not work and it seems that it is related to the conflicting files. 
Maybe also renaming after/syntax/vimwiki.vim is needed?

**Comment by Shougo** [comment]
> Maybe also renaming after/syntax/vimwiki.vim is needed?

It is not needed.
