### ISSUE TITLE
taskwiki templating

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#16]
A task as represented by taskwiki, has two fields displayed by default. This feature request is for a .vimrc config allowing custom task field selection and layout, including left and right justification.

Currently, the default task layout might be represented as;

<pre>
g:taskwiki_fields = '%desc (%due)
</pre> 

but a custom config might look like;

<pre>
g:taskwiki_fields = '%desc [%project] | (%due) %tags
</pre>

those on the right side of the "|" pipe would be right-justified, those on the left, left-justified, so that an example task with the above custom config might look like;

<pre>
* [ ] call Sue about piano lessons [music]         (2015-03-20) :skills:weekly:txn:
</pre>

**Comment by linuxcaffe** [comment]
some icing on this non-existent cake might be to adopt (piggy-back on) the taskwarrior column formats, so that the above example would be 
<pre>
g:taskwiki_fields = '%desc.truncated [%project.parent] | (recur.indicator %due) %tags
</pre>
which might look like;
<pre>
* [ ] call Sue about bagpipe lessons and tu... [music] :(R 2015-03-20) :skills:weekly:txn:

**Comment by tbabej** [comment]
Now this is quite complex. You need to keep in mind that the sync goes both ways, so for each field defined, taskwiki needs to learn:

a) How to parse it from the line
b) How to convert it to a string

Currently we solve a) by using a regexp that matches a line with a task, and b) is hardcoded to the format the regexp recognizes.

To make this generic, we would have to users enter regexps in the configuration, and b) would need to be solved too.

This probably *could* be done if we defined a clear set of building blocks, and for each of them define how to parse them in the core, however, this is a overkill for our currently quite small userbase.

If anybody steps in wanting this with PRs, I'll gladly collaborate.

**Comment by tbabej** [comment]
Some more thoughts:

* Having a global template for all the tasks does not make sense. For example, consider the template you proposed:

    g:taskwiki_fields = '%desc.truncated [%project.parent] | (%recur.indicator %due) %tags

This works very well for the ViewPort that looks like this:

    == Today's tasks | due.before: today ==
    * [ ] Important work task [Work]
    * [ ] Some home chore [Home]

where the projects are diverse and the showing up of the projects makes sense.

However, with a ViewPort like this one:

    == Work tasks | pro:Work ==
    * [ ] Work task 1 [Work]
    * [ ] Work task 2 [Work]
    ...

So we can see one global format will not work. This will have to be a per-ViewPort configurable setting, and since the definition is quite long, mutliple styles would have to be stored in the .vimrc and the ViewPort would only specify which style to use.

**Comment by tbabej** [comment]
Clearing this one out of backlog right now. It's not going to happen unless somebody steps in anytime soon.

**Comment by tbabej** [comment]
I am going to reconsider this one.

**Comment by linuxcaffe** [comment]
my "working" copy of this is https://github.com/linuxcaffe/taskwiki-template/tree/dev.
In the dev branch I removed non-taskwiki-related templates. This is significant because in master (vim-template with added taskwiki templates) templating would occur on creating almost any type of file,, but with all but taskwiki-related stripped out, it's actually usable for me. 

I still need to
- clean up the templates (they're too verbose, user-specific and inconsistent)
- pull changes from vim-template, merge dev to master
- better document the default locations and file-naming conventions. 
- improve gen-index script (https://github.com/linuxcaffe/taskwiki-utils)

before it could be considered usable

**Comment by tbabej** [comment]
Correct me if I'm wrong, but you're talking about file templates, while the issue talks about per-task templates (i.e. templates for representation of the tasks in the buffer), right?

**Comment by linuxcaffe** [comment]
OMG you're absolutely right, when this issue was filed (a year and a half ago) it was in reference to in buffer representation, and since then I have been working on file templates.

So the comments I made above would relate to file-templates, which is a different (if potentially related) and I should start a separate issue for that.

**Comment by tbabej** [comment]
Closing unless some brave soul volunteers to implement this.
