### ISSUE TITLE
taskwiki takes over default link rendering

### ISSUE THREAD

**Issue by beuerle** [tbabej/taskwiki#160]
The normal behaviour of vimwiki is to _render_ a link when the cursor is not on the same line, but to show the plain text when the cursor is on the same line, even if in normal mode.

When taskwiki is enabled it captures the normal rendering and only displays the plain text without rendering if the cursor is on the same line **and** vim is in `insert` mode.

1. normal vimwiki link rendering, cursor not on line (**taskwiki disabled**):
![2017-09-26_12 12 30](https://user-images.githubusercontent.com/10122039/30855721-2fd5fc84-a2b6-11e7-9aa2-1ed44f46a5eb.png)
1. normal vimwiki link rendering, cursor on line (**taskwiki disabled**):
![2017-09-26_12 12 36](https://user-images.githubusercontent.com/10122039/30855726-3669fbe0-a2b6-11e7-99b1-915796147932.png)
1. link rendering, cursor on line, `normal` mode (**taskwiki enabled**):
![2017-09-26_12 13 26](https://user-images.githubusercontent.com/10122039/30855729-3a7ac732-a2b6-11e7-8762-26bf181a9f53.png)
1. link rendering, cursor on line, `insert` mode (**taskwiki enabled**):
![2017-09-26_12 13 29](https://user-images.githubusercontent.com/10122039/30855737-3ef2501e-a2b6-11e7-832c-f9737917d5fa.png)

Is there a way to disable this, so that taskwiki does not take over the default rendering of links from vimwiki inside vim? Would it be possible to enable/disable this by setting, i.e. `let g:taskwiki_link_rendering="no"`?

**Comment by tbabej** [comment]
There is no setting (but could be). This is simply caused by taskwiki being too opinionated on the value of the concealevel, seel `after/syntax/vimwiki.vim:51`.

Lowering this to 2 using

    :setlocal conceallevel=2

should do for now as a workaround.

**Comment by beuerle** [comment]
the actual setting is not the `conceallevel`, but the `concealcursor`.

unsetting `concealcursor` with

```
:set concealcursor=
```

solves my issue. I can live with that, but maybe it would be worth to make a setting in taskwiki for that.

**Comment by tbabej** [comment]
Oh yes, I forget. The already existing setting `taskwiki_disable_concealcursor` is indeed the fix for the problem.h
