### ISSUE TITLE
Errors in JSON parsing after sync

### ISSUE THREAD

**Issue by jakobkolb** [tbabej/taskwiki#161]
Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tasklib/backends.py", line 319, in filter_tasks
    filtered_task._load_data(json.loads(data))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 23 (char 22)
```

Apparently, this is caused by syncing with taskwarrior on android, resulting in dependencies in the JSON database being formatted as

```JSON
depends:"&open;\"uuid1\",\"uuid2\", ... ,\"uuidN\"&close;"
```
as opposed to the old

```JSON
depends:"uuid1, uuid2, ..., uuidN"
```
How can make taskwarrior work with this format?

**Comment by tbabej** [comment]
We can't. This is a bug in the Android client, I recommend raising the issue with them. Also maybe filing a suggestion for taskd to reject such invalid updates would be helpful.

**Comment by tbabej** [comment]
As a workaround, I'd recommend editing the data files manually (they're in plaintext).

**Comment by jakobkolb** [comment]
For anyone running into similar Issues: I eventually solved this by manually fixing the data files as proposed by tbabej and installing a version of the android client that has the recent version of the taskwarrior binary but is unfortunately not yet released in the google play store (as of 2017-10-16) but can be found in f-droid: https://f-droid.org/packages/kvj.taskw/
