### ISSUE TITLE
Allow disable of task wiki processing for sections within file

### ISSUE THREAD

**Issue by hwine** [tbabej/taskwiki#164]
My use case is that I'm often developing a checklist within a document. (When I first integrated taskwiki and saved, that was exciting!) I use vimwiki for these efforts, as the proposed checklists render nicely in HTML.

For example, if there was an option for "only process checklists in viewports", that would meet my needs.

**Comment by bodograumann** [comment]
I simply use a different itemization marker for this use case:

```
- something
- not
- taskwiki
-related

* [ ] my taskwiki task
```

**Comment by hwine** [comment]
@bodograumann sorry I wasn't clear -- I want to mix vimwiki & taskwiki checklists (not plain lists) in the same document. But only have the "taskwiki" ones sync to taskwarrior.

**Comment by bodograumann** [comment]
No worries. My comment still applies. Currently taskwiki only handles items marked with an asterisk (`*`). So you can safely use

```
- [ ] item 1
- [ ] item 3
- [ ] item 42
```
and they are not turned into tasks. Of course `#` or the syntax for ordered lists would work as well.

**Comment by hwine** [comment]
@bodograumann Ohhh -- I missed that implication. Thanks for clarifying. I'll double check things, then probably close this.
