### ISSUE TITLE
Support markdown style headers for viewports

### ISSUE THREAD

**Issue by beuerle** [tbabej/taskwiki#165]
At the moment taskwiki only recognizes viewports defined inside vimwiki-style headers, but not markdown style:

```markdown
== home | project:home ==
* [ ] clean kitchen
* [ ] buy beer

## home | project:home

```

Would it be possible to recognize markdown style headers for viewports as well, if the syntax is set to `markdown` in `vimrc`?

#### Motivation:

Markdown renderers do not recognize the vimwiki style header, and hence fail to render the list:

![2017-11-15_10 47 48](https://user-images.githubusercontent.com/10122039/32829587-c9a875f4-c9f2-11e7-936a-dd6be1c9798a.png)

**Comment by thepith** [comment]
This functionality is provided #152 . Until the pull request is merged into the master, you can use the [fork from DancingQuanta](https://github.com/DancingQuanta/taskwiki/tree/extra-syntaxes) (use the `extra-syntaxes` branch. You then have to set
```
let g:taskwiki_syntax = 'markdown'
```
in you vimrc. It seems as if everything works fine.

**Comment by tbabej** [comment]
We should also make sure that we cover the folding case as described in #147

**Comment by jerri** [comment]
Just a small comment. Everything seems to work. But the `taskwiki_markup_syntax`-configuration-variable is not mentioned in the helpfiles. This should be added!
