### ISSUE TITLE
Taskwiki does not find tasklib when using anaconda

### ISSUE THREAD

**Issue by jakobkolb** [tbabej/taskwiki#169]
When starting Vimwiki, Taskwiki fails with 
```
Error detected while processing /home/jakob/Tools/.vim/bundle/taskwiki/ftplugin/vimwiki/taskwiki.vim:
line   31:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jakob/Tools/.vim/bundle/taskwiki/taskwiki/main.py", line 15, in <module>
    from taskwiki import cache as cache_module
  File "/home/jakob/Tools/.vim/bundle/taskwiki/taskwiki/cache.py", line 5, in <module>
    from taskwiki import viewport
  File "/home/jakob/Tools/.vim/bundle/taskwiki/taskwiki/viewport.py", line 6, in <module>
    from taskwiki import vwtask
  File "/home/jakob/Tools/.vim/bundle/taskwiki/taskwiki/vwtask.py", line 7, in <module>
    from tasklib import Task
ModuleNotFoundError: No module named 'tasklib'
```
Despite ```pip list``` referring to the conda environment as well as ```sudo pip list``` referring system level python show tasklib as being installed.

**Comment by Blake-LeBlanc** [comment]
Came to say I'm having the same issue. Let us know if you need any more information, happy to help!

**Comment by DancingQuanta** [comment]
My experience has shown the vim uses a python installation separate from anaconda. So this have an effect that there are two separate site-packages. So vim looks into one of these site-packages and not another because the python executable point to its site-package.
This is why vim that has not been compiled with anaconda python does not see packages installed in conda  environment.

So this is not taskwiki issue.

There is a simple solution, a number of them actually and I will write about them tonight.

**Comment by tbabej** [comment]
@DancingQuanta If the writeup happens, maybe we get it into README / documentation?

**Comment by szaffarano** [comment]
Hi, I've got this problem after updating my Linux environment.  Using:

- Miniconda 4.5.11
- Vim 8.1.0549-1

@DancingQuanta ¿how can I fix this Conda related issue?

Thanks in advance!

**Comment by szaffarano** [comment]
**UPDATED**: I've just installed [vim-conda](https://github.com/cjrh/vim-conda) Vim Plugin and now I can manage my Conda environments without any problem.

**Comment by joeweaver** [comment]
I know this is an old issue, but it was the closest thing I found to a solution after googling for days, it's also one of the top hits.

As DancingQuanta said, it has to do with where vim looks for python libs.  One workaround it to add a ```PYTHONPATH``` environment variable which vim can use to search for libs.

In my specific case, adding this line to my .zshrc fixed the issue (you'll of course want to edit the specifics for you path):
```export PYTHONPATH="/home/joe/miniconda3/envs/py37/lib/python3.7/site-packages"$PYTHONPATH```

**Comment by newptcai** [comment]
> In my specific case, adding this line to my .zshrc fixed the issue (you'll of course want to edit the specifics for you path):
> `export PYTHONPATH="/home/joe/miniconda3/envs/py37/lib/python3.7/site-packages"$PYTHONPATH`

This probably should be
```
export PYTHONPATH="/home/joe/miniconda3/envs/py37/lib/python3.7/site-packages":$PYTHONPATH
```
Also note the exact path depends on which environment you are in.
