### ISSUE TITLE
bind <CR> to invoke TaskWikiInfo

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#17]
It would be very convenient if, in normal mode, and only when over a task, hitting <CR> invoked TaskWikiInfo.

**Comment by tbabej** [comment]
Why not let users define bindings themselves?

**Comment by linuxcaffe** [comment]
I don't see <CR>  --> info binding as a personal preference thing, as much as half of a toggle.

**Comment by tbabej** [comment]
Fixed in master.
