### ISSUE TITLE
Interleave free form text and todos for a particular project

### ISSUE THREAD

**Issue by MartyLake** [tbabej/taskwiki#170]
Hello !

As I work on debugging scenarios, I like to write my thoughts, from which I extract TODOs. I know a line starting with "* [ ]" will create a todo anywhere in a wiki file.

How can I specify that all todos in this bloc of text or file belong to a specified project ?

**Comment by tbabej** [comment]
It should be sufficient that the closest header above the task contains default specifying the project.

    === Project X | some-nonsense-filter-so-that-zero-tasks-match-this-otherwise-they-get-generated-here | project:ProjectX ===
    This is some free form text.
    This is some free form text.
    This is some free form text.
    This is some free form text.
    This is some free form text.

    This is some free form text.
    This is some free form text.
    This is some free form text.
    This is some free form text.

    * [ ] And this should have project:ProjectX assigned

**Comment by MartyLake** [comment]
It works !!! Thanks a lot !
