### ISSUE TITLE
TaskCollectionNode cannot have multiple parents

### ISSUE THREAD

**Issue by ckeschnat** [tbabej/taskwiki#171]
taskwiki throws an error when a task depends on multiple others

How to recreate:
Viewport:
`== Work | +work ==`

Add tasks:
$  task add Common_Subtask +work
Created task 1.
$  task add Maintask1 +work dep:1
Created task 2.
$  task add Maintask2 +work dep:1
Created task 3.

Opening the wiki now results in:
```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.vim/bundle/taskwiki/taskwiki/main.py", line 638, in <module>
    WholeBuffer.update_from_tw()
  File "/root/.vim/bundle/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/root/.vim/bundle/taskwiki/taskwiki/decorators.py", line 10, in wrapped_function
    original_function(*args, **kwargs)
  File "/root/.vim/bundle/taskwiki/taskwiki/main.py", line 42, in update_from_tw
    c.evaluate_viewports()
  File "/root/.vim/bundle/taskwiki/taskwiki/cache.py", line 216, in evaluate_viewports
    port.sync_with_taskwarrior()
  File "/root/.vim/bundle/taskwiki/taskwiki/viewport.py", line 376, in sync_with_taskwarrior
    sort.TaskSorter(self.cache, self.tasks, self.sort).execute()
  File "/root/.vim/bundle/taskwiki/taskwiki/sort.py", line 37, in execute
    child.parent = node
  File "/root/.vim/bundle/taskwiki/taskwiki/sort.py", line 154, in parent
    raise ValueError("TaskCollectionNode %s cannot have multiple parents" % repr(self))
ValueError: TaskCollectionNode Node for with ID: 1 cannot have multiple parents```

**Comment by tbabej** [comment]
This is a known design choice, see #75 for further explanation.

**Comment by mareq** [comment]
The comment above says that there is further explanation in #75, but I can not see much of a discussion there, except that "Dependency hierarchy with indentation is a killer feature". Yes, indeed it is, but how does that explain design choice of not handling multiple dependent tasks correctly?

I can kind-of understand that it may lead to problems with infinite renderings due to circular dependencies. But that can be solved easily: expand the subtasks of given task if and only if it is being rendered under its first parent, otherwise stop expanding this branch.

**Comment by MarshCastle** [comment]
OK - I get this, but I keep coming across it using VimWiki. This would be fine, but - for me - it can take a very long time to find out which task has two parents.

Does anyone know a recipe to investigate which are the problematic tasks?

...Please... :pray:

**Comment by liskin** [comment]
@MarshCastle this should do the trick:

```
task export | jq -r '.[] | .uuid as $uuid | .depends | values | split(",")[] | $uuid + " " + .' | sort --key=2 | uniq -D --skip-fields=1
```

**Comment by mareq** [comment]
@liskin: Thank you for that.

Still, I am using exclusively taskwiki plugin for managing the tasks and I am getting this error relatively frequently. I understand that it is the design choice not to allow multiple parents, but taskwiki should make sure that it does not create such situation itself (now it does on occasion, which should be considered a bug that needs to be fixed?).

**Comment by joeweaver** [comment]
It may be useful to have the error message lead directly to information on the design choice.

**Comment by MarshCastle** [comment]
@liskin - thanks for that. I get a parse error with it, but I get the point and can maybe work out a way 'round that (a bit time poor atm - sorry for the slow response :( _ have to learn a bit of jq! :)

I'm with @joeweaver though - would be helpful if the error could refer to the id on the error message (is that possible on a backtrace (I'm not quite a dev...)
