### ISSUE TITLE
Marking task as done and then saving file resets status to pending

### ISSUE THREAD

**Issue by brendanator** [tbabej/taskwiki#176]
If I run `:TaskWikiDone` and then save the file the status is reset to pending

Here's the info on the task
```
2018-04-30 08:50:54 End set to '2018-04-30 08:50:54'.
                    Status changed from 'pending' to 'completed'.
2018-04-30 08:50:56 End deleted.
                    Status changed from 'completed' to 'pending'.
```

**Comment by brendanator** [comment]
There was a second viewport also containing this task in the file that was overwriting the change

**Comment by brendanator** [comment]
This is definitely an issue as I might easily want to have the task appear in 2 viewports.

Making a change to the any view of a task should propagate to the others

**Comment by dustinosity** [comment]
I was having this problem as well, but with one task that was not in a viewport and one that was in a viewport in the same file. The viewport task seemed to always take precedent over the free floating task.

**Comment by nagakiran** [comment]
Made a patch to fix this. Let me know your comments.
https://github.com/nagakiran/taskwiki/commit/808ee8f14693bdc2614598da27296f02be9106fe

**Comment by tbabej** [comment]
@nagakiran Maybe we should convert this to a proper PR?

**Comment by tbabej** [comment]
This is actually another case of the same problem as #113

**Comment by sdondley** [comment]
This patch appears to work for *modified* tasks. But if a task is *deleted* it pops back into the viewport.
