### ISSUE TITLE
new command :TaskWikiDelete [ids|uuids]

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#18]
Currently, deleting a task in a ViewPort or a wiki, does not delete the task from pending.data, and this is good.
But if you actually wanted to delete a task or tasks, the command :TaskWikiDelete, on a single task or visually-selected group, would make that possible. 
The command could also use trailing ID(s) or UUID(s), instead.

**Comment by tbabej** [comment]
Added ```:TaskWikiDelete``` command, that accepts range or task currently under the cursor.
