### ISSUE TITLE
Leader Mappings Not Working

### ISSUE THREAD

**Issue by sh78** [tbabej/taskwiki#182]
Strange issue here. None of the default leader key maps have never worked for me.

I thought it must be a conflicting mapping, but there doesn't seem to be any:

```vim
:map <leader>tm

" prints:
" v  <Space>tm    @:TaskWikiMod<CR>
" n  <Space>tm    @:TaskWikiMod<CR>
" Press ENTER or type command to continue
```

Also tried:

- Changing my leader map back to default ('\') and restarting
- Manually defining the same mapping in vimrc (`nnoremap <leader>tm :TaskWikiMod`)

Nothing worked.

Turns out it's because of this:

```vim
" switch colon and semicolon
nnoremap ; :
nnoremap : ;
vnoremap ; :
vnoremap : ;
```

The strange part is that other mappings which also use a plain `:Command` binding
do work. For example:

```vim
" this works
nnoremap <Leader>tb :TagbarToggle<CR>
```

I do notice that the results printed by `:map` for taskwiki have `@` next to
them. I think that just means they are for the local filetype...?

```vim
:map <leader>tb

" prints:
n  <Space>tbm   @:TaskWikiBurndownMonthly<CR>
n  <Space>tbw   @:TaskWikiBurndownWeekly<CR>
n  <Space>tbd   @:TaskWikiBurndownDaily<CR>
n  <Space>tb   * :TagbarToggle<CR>
```

Here's a link to my [vimrc](https://github.com/sh78/dotfiles/blob/d01485a25f03652a33e2449e230e784cfffe3f0c/.vimrc#L1). It's including files from [here](https://github.com/sh78/dotfiles/tree/master/.vim/user).

I'm using terminal vim with the latest vimwiki and taskwiki from master.

**Comment by tbabej** [comment]
Strange indeed! I have not encountered this behaviour, but will keep you posted if I manage to find time to try to reproduce this.

**Comment by sh78** [comment]
Thanks Tomas!
