### ISSUE TITLE
Version tags for the repository

### ISSUE THREAD

**Issue by williamjameshandley** [tbabej/taskwiki#184]
Would it be possible to tag significant commits with version numbers. I maintain the [AUR arch linux](https://aur.archlinux.org/packages/vim-taskwiki/) repository for taskwiki, and keeping everything up-to-date would be a lot easier if tags were being used.

**Comment by tbabej** [comment]
Sure! Right now the development is pretty stalled, though. I can tag a version once we have a smaller cleanup (say, expanding tests to Python3.7, and verifying new isues that are up in the tracker).

**Comment by williamjameshandley** [comment]
Hi there. Is there any possibility we could resurrect this issue?

**Comment by tbabej** [comment]
Sure. I tagged the current master as `1.0.0`. Thanks for checking back.
