### ISSUE TITLE
[error?] tasks seem uneditable if you try to edit them, then make no changes, then run :bd

### ISSUE THREAD

**Issue by arooni** [tbabej/taskwiki#187]
Not sure if this is a flow that no one uses but me but say

you have your viewports set up you take these steps

1)  leader te (edit)
2) decide there's nothing you want to edit
3) run :bd [because you're not sure how to get out of this window w/o making changes.. you tried <leader>td for being done -- didn't work
4) go back to your task list
5) decide you want to edit the task again; you see:

Filter: ( ( ( uuid = 3bc06e65 ) ) )
Task is already being edited.

[Process exited 2]

not sure how to proceed from here

**Comment by tbabej** [comment]
Hey @arooni , :TaskWikiEdit calls `task edit` which launches a separate vim instance with temporary file that is being edited. For that process to finish, you have to close the vim process, i.e. `:q!` - which will return you back to your first vim process.

Let me know if this does not resolve the issue!

**Comment by arooni** [comment]
Hey thanks for the quick response!  it totally resolves the issue; the only
thing is after the edit; i dont see the changes reflected on the tasks
title on the main index.wiki page.  is there a way to 'refresh' or repull
the tasks (other than closing the file and opening it again) which then
seems to do the right thing

may today be the best day of your life,
-------
david parkinson
founder - aroonilabs.com
blog - brofist.com
twitter - @brofist <https://twitter.com/brofist>

**Comment by arooni** [comment]
aparently that's what :TaskWIkiBufferLoad is for

may today be the best day of your life,
-------
david parkinson
founder - aroonilabs.com
blog - brofist.com
twitter - @brofist <https://twitter.com/brofist>
