### ISSUE TITLE
new command :TaskWikiMod < mods >

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#19]
Using this command is like issuing 'task mod < mods > on the task under the cursor, or visually-selected group of tasks, and would allow modification of any attribute, without leaving the wiki and losing focus. Mods should be reflected in any ViewPort on the page, immediately after making changes. 

note* User with vim-taskwarrior already installed, can already do something similar :TW < anything >

**Comment by tbabej** [comment]
Implemented by ```:TaskWikiMod``` command, which either takes passed modstring, or prompts user to give one.
