### ISSUE TITLE
[feature request] allow for custom udas [like time estimates] display on the task description

### ISSUE THREAD

**Issue by arooni** [tbabej/taskwiki#191]
I try to use swag minute estimates for tasks to both ensure that I don't schedule too much for a given day but also to sort of compete against myself to finish the task by the estimate.

I'm aware that I can hit <CR> and get an info pane for each task separately, but it'd be great if we could specify custom uda's that really matter for us and adjust the data that's displayed on the wiki page... 

perhaps have a template type approach where we could insert the standard data we'd like to see displayed not unlike what taskwarrior does in its own config file.  

thanks so much again for this great software.

**Comment by tbabej** [comment]
@arooni , @amitbeka is correct. I will close this as a duplicate for now, but great to see the support for that functionality!
