### ISSUE TITLE
Hide compeleted tasks

### ISSUE THREAD

**Issue by Chickensoupwithrice** [tbabej/taskwiki#195]
Hi there, 
I have just started using taskwiki but I have been using taskwarrior for some time now. I have managed to import my tasks using the viewports. However when I try something like status:pending it doesn't hide all the tasks that are completed. Is this currently possible with TaskWiki? 
Would be awesome if so, but if not I could look into making a PR? I've never worked with vim extensions before though. 
Thanks

**Comment by nambit** [comment]
Putting +PENDING in the viewport works for me and hides all completed tasks.

**Comment by tbabej** [comment]
@nambit has the correct answer here. The `status:pending` should work also, does one work and the other not?

**Comment by sdondley** [comment]
Might there be a way to keep tasks around that were completed recently to help generate a report of what was done?

**Comment by sdondley** [comment]
To answer my last question, that can be done with a taskwarrior filter. For example:

`# Tasks | status:completed end:yesterday`

**Comment by tbabej** [comment]
As all the questions were answered, closing this for now.
