### ISSUE TITLE
UUID as link

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#2]
imho, the UUID should be presented as a wiki-link in the form of 

[[task: bfea17e6-778a-43e0-8508-a7d29b39673d|ID]]

with the task ID (52, in this example) presented as the description.

This could have several advantages
- less "visual noise", as only a few characters are seen (unless the cursor is over it)
- task ID is immediately available, so regular tw actions can be performed 
- link gets syntax highlighting
- special link handler can be used to "follow the link" and get task info.

**Comment by linuxcaffe** [comment]
The special link handler could be used to open an info window, in the same way that vim-taskwarrior does it, when you hit "enter" over a given task. (https://github.com/farseer90718/vim-taskwarrior)

**Comment by tbabej** [comment]
Info window does not have to be connected with the uuid being link, we can simply use a keymap to open the window. I suggest this is split as a separate issue, since it does not have to be related.

**Comment by tbabej** [comment]
Using ID as concealment characters for UUID seems interesting (as opposed to showing nothing as it is now). However, I am worried about the ID reassigment. If a task was completed in the meantime, and IDs were re-assigned, you might manually edit a different task than you think you are editing.

**Comment by linuxcaffe** [comment]
I agree that non-static IDs is an issue, but not a show-stopper. Checking IDs against UUIDs every time the file is opened, or saved, is probably the best that could be done from the wiki side of the fence.

**Comment by linuxcaffe** [comment]
I think teranex may have tried to apply ID as concealment character, and iirc, vim only allows a single character for this function. This is as opposed to using the vimwiki's link-with-description function, which has no such limitation.

**Comment by linuxcaffe** [comment]
Once a task is completed, it will still be seen in a wiki (marked as [X] completed) but it will lose it's ID. When that happens, uuid.short could be used as the description part.

**Comment by linuxcaffe** [comment]
In thinking about it, this issue ia actually a duplicate, or aspect of #5. 
Rather than being a special case, it is more simply the task: scheme with a uuid as the query, as in 

<pre>
== [[ID|task: uuid]] ==
</pre>
resolving in a single task, and (like task) running the info report (:TWReportInfo or :TWWInfo)

**Comment by tbabej** [comment]
Behaviou can be configurable, user can be able to switch between complete concealment of UUIDs, or usage of UUID/ID links.

**Comment by tbabej** [comment]
Now that we have the ```:TaskWikiInfo``` command, which can the user bind to any keymap (i.e. <CR>), I don't think this is necessary anymore.
