### ISSUE TITLE
use vim-airline, if installed

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#20]
Vim airline can provide a valuable, information-rich status line. 
Vim-taskwarrior can use it very effectively, if it is installed, but it's not a requirement, and I think TaskWiki could take advantage of it too.

**Comment by tbabej** [comment]
What useful info could be shown there?

**Comment by linuxcaffe** [comment]
maybe context filter in use? total # of tasks on the page? taskd status? big warnings?

**Comment by tbabej** [comment]
* Context filter is not really relevant to the particular taskwiki file open.
* Taskd status the same.
* # of tasks is somewhat arbitrary.

I'd recommend you to switch to powerline - it's python, and has status line for more than vim alone.

I already have a segment in powerline to display the active task, which looks like:

    def active_task(pl):
        tw = TaskWarrior()

        active = tw.tasks.filter(uuid='+ACTIVE')[0]

        return [{
                'contents': active['description'],
                'highlight_groups': ['environment'],
        }]

**Comment by tbabej** [comment]
Nevertheless, implementing a airline support is just a matter of dropping a extension file into a correct dir, so if somebody does a PR, I will not object.

Here is a good example: https://github.com/farseer90718/vim-taskwarrior/blob/master/autoload/airline/extensions/taskwarrior.vim

**Comment by linuxcaffe** [comment]
The current context affects the TaskWikiProjects and TaskWikiProjectSummary commands, although it probably shouldn't (?)

**Comment by tbabej** [comment]
Yes, that's a different issue.
