### ISSUE TITLE
taskwiki doesn't seem to support neovim 0.3.2

### ISSUE THREAD

**Issue by crocket** [tbabej/taskwiki#200]
I upgraded neovim from 0.3.1 to 0.3.2

taskwiki stopped working.

![2019-01-10_thu_13 55 36](https://user-images.githubusercontent.com/748856/50972838-ecf80e00-152a-11e9-921e-f7de6db2fe43.png)

**Comment by crocket** [comment]
After upgrading neovim-python-client from 0.2.6 to 0.3.1, this issue was fixed.

**Comment by tbabej** [comment]
Maybe we could do this check automatically? Not sure if it's worth the effort, I mean, it probably belongs on the level of neovim itself.

**Comment by crocket** [comment]
I think it was incompatibility between neovim-0.3.2 and neovim-python-client-0.2.6. I guess this issue should be dealt with by specifying version ranges in linux distribution packages.

**Comment by crocket** [comment]
I just found https://github.com/neovim/neovim/pull/9344 which was merged last month.
The next version of neovim will not present me a confusing error message.

**Comment by crocket** [comment]
It seems the esoteric error message is still not fixed. I filed https://github.com/neovim/neovim/issues/9485
