### ISSUE TITLE
taskwiki doesn't support https://github.com/JensErat/task-relative-recur

### ISSUE THREAD

**Issue by crocket** [tbabej/taskwiki#201]
When I press `\td` or `\tD` on tasks with `relativeRecurWait` set,

* the task is completed
* nvim freezes
* `on-modify.relative-recur` fails to regenerate a waiting task.

**Comment by tbabej** [comment]
Is it possible this is a bug in the hook? It not handling the commands issued by taskwiki could be the problem.

In general taskwiki supports hooks, so this issue is specific for this plugin. I'd recommend implement some logging in the hook to see where it gets hung.

**Comment by crocket** [comment]
I think I'd rather close this issue because I don't want to maintain an old hook. I will stop using the hook.
