### ISSUE TITLE
Is there a chance to have this working without vimwiki?

### ISSUE THREAD

**Issue by nkakouros** [tbabej/taskwiki#213]
I am using simple markdown files with a couple extra plugins and have effectively A+ markdown support plus vimiwiki functionality without vimwiki. I was wondering if there is any chance that this project can work without vimwiki. If not, is adding support for simple markdown files a non-trivial task?

**Comment by tbabej** [comment]
Decoupling from vimwiki might not be hardest of endeavours, but it would require careful thought.

**Comment by tbabej** [comment]
As the question was answered, closing this for now. Of course, open to contributions to decouple TW and VW.
