### ISSUE TITLE
taskwiki is hiding markdown syntax on vimwiki

### ISSUE THREAD

**Issue by sdondley** [tbabej/taskwiki#214]
Integration with markdown seems to be undocumented. Looking for guidance. I managed to find something here in the issue queue about `let g:taskwiki_markup_syntax = 'markdown'` but that didn't fix the problem:

Typically, when viewing a document with vimwiki and the cursor is on a line with a link, the markdown syntax will be revealed for that link, making it easier to delete a link. With the taskwiki installed, it becomes much more difficult to remove a link's markup.

**Comment by mschout** [comment]
I'm pretty sure that vimwiki is to blame here.  I don't like the link hiding that vimwiki does myself.  I put `set syntax=markdown` in `.vim/after/syntax/vimwiki.vim` and I don't have any problems after that.

**Comment by sdondley** [comment]
It turns out there is a variable for this:

*taskwiki_disable_concealcursor*
    If set to any non-empty value (such as "yes"), taskwiki will not conceal
    characters on the cursor line in normal mode via `concealcursor=nc`.

**Comment by badlandz** [comment]
This sounded like my problem, but that option doesn't seem to change the behavior for me.
