### ISSUE TITLE
:TaskWikiInfo [ID|UUID]

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#22]
Currently, invoking ':TaskWikiInfo 142' generates an "E488: Trailing characters" error, but I think it would be swell if it opened the info-window of 142, instead.

**Comment by tbabej** [comment]
What would be the use for taskwiki users? IDs are not displayed anywhere in the tasks, and UUIDs are concealed - much easier to select the task visually.

**Comment by linuxcaffe** [comment]
TaskWiki, while awesome, is not the only game in town, and almost all other interfaces use ID as the primary identifier for a task. Yes, it's a moving target, and the ID can and will change, there's still a strong possibility that a user might know a task ID, and want to see the corresponding info. If the TaskWikiInfo command could use a trailing ID argument, it won't affect the current behavior, and it might be handy.

**Comment by tbabej** [comment]
I don't think this fits with the vision for the TaskWiki - it mostly operates only with what is displayed. Implemeting this is super easy - it just does not make much sense.

**Comment by linuxcaffe** [comment]
agreed
