### ISSUE TITLE
ability to add a tag to a task from command line mode in vim

### ISSUE THREAD

**Issue by nathanbraun** [tbabej/taskwiki#223]
Hi there, great plugin -- I use it every day.

I was wondering if it'd be possible to add a tag to task from the command line.  I.e., have the cursor over some task, type `:TaskWikiAddTag computer` and have it add that tag to my task.

Right now I'm doing this with the interactive TaskWIkiChooseTag command but with my workflow most times I'm picking the same tag and so it'd be great if I could map this to something and make the process a little quicker.

Thank you!

**Comment by tbabej** [comment]
Hi @nathanbraun ! Glad to see that you find taskwiki useful.

I'd recommend that you use `:TaskWikiMod` for this - i.e. `:TaskWikiMod +computer` should do the trick.

**Comment by nathanbraun** [comment]
Awesome, not surprised it's already built in, thanks!
