### ISSUE TITLE
Error inserting new tasks

### ISSUE THREAD

**Issue by tom-doerr** [tbabej/taskwiki#228]
When I press `o` in line 2 to insert a new task below task `abc`
```
  1 = test =                                                                    
  2 * [ ] abc                                                                   
  3 * [ ] def                                                                   
  4                                                                             
  5    
```
I end up with this:
```
  1 = test =                                                                    
  2 * [ ] abc                                                                   
  3 * [ ] * [ ] def  #58fcaad2                                                  
  4                                                                             
  5 * [ ] def                                                                   
  6                    
```
I can still add tasks without an issue at the end of the list,   this makes it hard to insert dependencies when I need to add them in the middle of the list.
but its difficult to add dependencies in the middle of the list.

Here's my vimrc: [https://github.com/tom-doerr/dotfiles/blob/master/vimrc](url)

Any guess what the issue could be?

**Comment by tom-doerr** [comment]
Turns out the `vim-auto-save` plugin caused the issue.
It could also be responsible for #227.
Is there a way of automatically saving without causing issues?

**Comment by tbabej** [comment]
I guess you could disable `autocommands` that taskwiki sets that fire the `TaskWikiBufferSave` and `TaskWikiBufferLoad` commands, and just do it manually (that is, the sync with TW would be manual).

**Comment by tom-doerr** [comment]
Thanks! Adding the line `autocmd BufRead *.wiki let g:auto_save = 0` to my vimrc solved it.
