### ISSUE TITLE
new command: TaskWiki < filter > < command > [ < mods > | < args > ]

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#23]
This is analogous to the vim-taskwarrior :TW command, which is effectively like having a task-shell within vim. The major difference would be that it will operate on visually-selected tasks, otherwise, it is a global command. It does _not_ normally focus on the task below the cursor, unless it is visually selected.
Just as in task cli, precautions against BBQing you whole data-set, with "This will apply to all tasks in the database, are you NUTS?? (yes/no)" warning messages

**Comment by tbabej** [comment]
The global version of the command does not make much sense to me - you can just run:

    ! task <whatever>

Now the version of the command, which uses a range/current task might be a good workaround for things not yet/not ever implemented.

**Comment by linuxcaffe** [comment]
That all makes sense, :! task is right there.
a better approach might be "options for the visually-selected.
