### ISSUE TITLE
reduce the number of commands by using trailing annual, monthly, weekly, daily arguments

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#24]
The recent flurry of TaskWiki commands is stupendous. Now there is a command for everything, but especially if you are using tab-completion, tabbing through the commands, imho, there are now more commands than necessary. 

namely;
* TaskWikiBurndownDaily
* TaskWikiBurndownMonthly
* TaskWikiBurndownWeekly
* TaskWikiGhistoryAnnual
* TaskWikiGhistoryMonthly
* TaskWikiHistoryAnnual
* TaskWikiHistoryMonthly

The way task cli handles it, is to allow "daily, weekly, monthly, annual" as arguments, following the command, and one of them is the default, if no argument is used. So instead;
* TaskWikiBurndown [daily|monthly|weekly] defaults to weekly
* TaskWikiGhistory [annual|monthly] defaults to monthly
* TaskWikiHistory [annual|monthly] defaults to monthly

**Comment by linuxcaffe** [comment]
If there were command re-naming going on, I might suggest one more small change:
s/TaskWikiProjectsSummary/TaskWikiSummary/
yes, the summary report is project-centric, but there is other data in there, and the shorter version would be more clearly differentiated from the TaskWikiProjects command. (and slightly quicker to invoke)

**Comment by tbabej** [comment]
We can't really do that, since all of these commands already accepts arguments, which are transformed into TW filter. Daily/monthly/weekly are valid words to use in a filter.

**Comment by linuxcaffe** [comment]
good reason!
