### ISSUE TITLE
Buffer switching breaks concealment for markdown wikis

### ISSUE THREAD

**Issue by pwsiegel** [tbabej/taskwiki#253]
Here's the setup.  My vimrc looks like this:
```
    let g:vimwiki_list = [
        \{'path': '~/testwiki', 'syntax': 'markdown', 'ext': '.md'}
    \]
    let g:taskwiki_markup_syntax = "markdown"
```
The file `~/testwiki/index.md` looks like this (without concealment)
```
# Test | project:myproject
* [ ] Task 1  #1234abcd
* [ ] Task 2  #5678efgh
```
Now, I launch vim and open a buffer (any buffer will do).  I type `<leader>ww` to open up my vimwiki above and I see what I expect:
```
# Test
* [ ] Task 1
* [ ] Task 2
```
Everything is great!  Then I switch back to my previous buffer using `:bp`, and then back to my wiki using `:bn`.  Now all of the beautiful concealment and highlighting is gone, and it looks like the "without concealment" code block above.  Based on my experiments, this happens only with markdown wikis - everything works as expected for wikis with the default markup syntax.

If this is a bug and I'm not just missing something, I'd be happy to try to fix it, though I would need some guidance on where to start looking.

Thanks!

**Comment by ard0gg** [comment]
I am having a similar issue where my viewport filters are not being concealed. Were you able to find a solution to this issue?

**Comment by pwsiegel** [comment]
Never mind - the problem was on my end.  I had some settings in my vimrc which sets the `filetype` to `markdown` and makes some syntax highlighting changes when `BufEnter` is triggered on a *.md file.  When I disable these settings, this plugin works exactly as it should.
