### ISSUE TITLE
Using custom todo symbols breaks taskwiki

### ISSUE THREAD

**Issue by skbolton** [tbabej/taskwiki#260]
Vimwiki has the option of defining custom todo symbols.[here](https://github.com/vimwiki/vimwiki/blob/64c9f3d36d632b1657616c06ea8f08f14cf6438d/doc/vimwiki.txt#L2411)

When using this feature task wiki gets into weird states when completing todos.

**Comment by tbabej** [comment]
Yeah, taskwiki currentl does not support custom todo symbols.
