### ISSUE TITLE
use "*" in ViewPort to mean "default = filter"

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#28]
Having some part of the ViewPort filter in the default, makes sense, to prevent new tasks from seeming to disappear. For example; 
<pre>
=== World Domination | project:dominate +world | project:dominate +world ===
</pre>
and the new tasks created under this ViewPort will be listed.
This RFE is for a short-hand for those cases (like the example above) where the defaults are a duplicate of the filter, which should be a fairly common occurance. The example above could then entered as;
<pre>
=== World Domination | project:dominate +world | * ===
</pre>

**Comment by tbabej** [comment]
I just started using taskwiki, after going out of this implementation frenzy, and I would even take more radical standpoint.

The defaults should always be inherited from the filter by default:
* writing the (mostly) duplicate definition is tedious
* viewport definition then gets very long and eventually wraps over two lines
* the sensation of adding a new task and having it disappear is suprising and annoying

However, not every filter is a valid modstring, for example:

    project:Home +PENDING due.before:now

cannot be directly converted into a TW modstring. So the correct move here is to ehance defaults parser to be able to recognize and reject:

* virtual tags
* attributes with modifiers

**Comment by linuxcaffe** [comment]
Alright, I tend to agree that default meta is often the same as filter. I agree to that some types of filter elements are never suitable as default meta elements. 

How about this for a compromise;
by default, convertible attributes from the filter (not virtual or with attmod) are added as meta, to any newly created task.
EXCEPT when added separately after the pipe. In other words, the syntax we are using now (title|filter|defaults) is still used, but the third element (defaults) is only used to override the filter elements.
<pre>
== This is a title | project:foo +DUE == (will assign project:foo as defaults)
== This is a title | project:foo +DUE | == (will assign no defaults)
== This is a title | project:foo +DUE | project:bar +baz == (will assign project:bar +baz as defaults)
This still allows the user to create new tasks that will seemingly disappear, but that will have to be explicitly configured, and is logically consistent.

**Comment by tbabej** [comment]
First and third case is what I envisioned. However, what is the use case for the

    == This is a title | project:foo +DUE | == (will assign no defaults)

syntax? If you want to just add a new task, without any defaults, you can type

    * [ ] Random task without any defaults

anywhere in the file, save the file, and delete the line, instead of creating a viewport that makes new tasks disappear.

**Comment by linuxcaffe** [comment]
fair 'nuff! That makes sense. 
Why use a ViewPort for something that doesn't belong in the ViewPort? (rhetorical) 
I suppose I was following the logic of the syntax; override with nothing, but I don't have a related use-case.

**Comment by tbabej** [comment]
Implemented in master.
