### ISSUE TITLE
allow newly created tasks to be entered with arbitrary metadata

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#29]
While TaskWiki displays only a limited amount of metadata (description, due:date, started) but tasks _could_ be entered with any metadata.  As soon as the new task(s) are processed, that metada will be hidden, like usual.
<pre>
== Make RFE example | project:taskwiki +RFE | project:taskwiki ==
* [ ] Existing task 1
* [ ] Existing task 2
* [ ] area:software +RFE depends:412 -- New task desciption
</pre> 
Using "--" to precede the description should make it easier (possible) to parse, as soon as taskwiki processes the new task(s), they are displayed as usual, with the extra metadata is hidden, like
<pre>
* [ ] New task description
</pre>

**Comment by tbabej** [comment]
Interesting approach. I have been planning to solve this problem by adding a ```:TaskWikiEdit``` command, so the workflow would be to add the task, save it, and run the edit command, which allows you to add/edit any attribute.

This, however, seems more straightforward, I like it. I'll try to do my best to make both approaches work.

**Comment by tbabej** [comment]
The probem with this, however, is the following:

* all new tasks entered manually will have the metadata saved and concealed
* the tasks generated by the viewport would not

This introduces a inconsistency. If we wanted to fix it, we would have to make it configurable (per viewport) what kinds of metadata is to be shown in the tasks generated, which complicates the feature a lot, and is quite close to the taskwiki templating proposal.

Therefore I think we should accept the modstring, but not conceal it - we should make it disappear after applying the changes.

**Comment by tbabej** [comment]
To verify that the changes have been applied, user can just toggle the ```:TaskWikiInfo``` command.

**Comment by linuxcaffe** [comment]
most excellent!

**Comment by tbabej** [comment]
Fixed in master.

**Comment by linuxcaffe** [comment]
This feature seems not to be working anymore. After attempting
<pre>
* [ ] Do this thing -- area:legal
</pre>
throws this error;
<pre>
Error detected while processing BufWrite Auto commands for "*.wiki":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/djp/dotfiles/vim/bundle/taskwiki/taskwiki/taskwiki.py", line 56, in update_to_tw
    cache.load_vwtasks()
  File "/home/djp/dotfiles/vim/bundle/taskwiki/taskwiki/cache.py", line 170, in load_vwtasks
    self[i]  # Loads the line into the cache
  File "/home/djp/dotfiles/vim/bundle/taskwiki/taskwiki/cache.py", line 77, in __getitem__
    vimwikitask = vwtask.VimwikiTask.from_line(self, key)
  File "/home/djp/dotfiles/vim/bundle/taskwiki/taskwiki/vwtask.py", line 203, in from_line
    modifications = util.tw_modstring_to_kwargs(modstring)[0]
</pre>

**Comment by tbabej** [comment]
As noted in doc/taskwiki.txt, please update your installation before submitting a bug report to verify it has not been fixed already.

This issue was fixed.

**Comment by linuxcaffe** [comment]
why so it is! thanks!
