### ISSUE TITLE
traceback link in task annotation 

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#3]
The original vimwiki-tasks features the option to embed a "traceback" link to the wiki file, in an annotation of associated tasks. This enables the user (using tw) to find those tasks that are also represented in a wiki, and b) easily follow those links to the wiki-file, using taskopen. (https://github.com/ValiValpas/taskopen)

The annotation should look something like "wiki: path/to/file.wiki", using the "annotation label" convention.

**Comment by tbabej** [comment]
Might be useful. However, we should use UDAs instead of annotations.

**Comment by tbabej** [comment]
After a lengthy discussion, I agree it might be useful to use annotations even though it will visually clutter the TW reports, as a ecosystem of other tools leveraging metadata in annotations already exists.

If this feature gets implemented, it should:

a) Be optional.
b) Provide a option for storage for the link (UDA vs. annotation)

**Comment by linuxcaffe** [comment]
If something like #7 is implemented (annotations displayed/ created as bullet points) AND the wiki traceback link is added to task as an annotation, then the option NOT to display that annotation, from inside the file that the link is pointing to (totally redundant) THAT annotation could be hidden, in that case.

**Comment by tbabej** [comment]
This is no longer applicable as we decided to make a effect of per-task command.
