### ISSUE TITLE
check requirements

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#30]
TaskWiki has several requirements, and may not operate correctly if these dependencies are not installed, or at their minimum versions. This RFE is for a diagnostic routine that tests for these requirements, and generates a warning message, or throws an error, if these requirements are not met.

**Comment by tbabej** [comment]
The only hard requirements is the tasklib version, which will be 0.10.0 if I can get Rob to release soon. And I haven't tested with non-dev vimwiki, but I suspect it's broken in various ways.

Regarding the TaskWarrior version, we should be fine with anything that tasklib supports, that is 2.1.1+

**Comment by tbabej** [comment]
Fixed by 5a5b5b3c915b13a3fab2611d695d7b07206a299d.
