### ISSUE TITLE
allow reportname, appended to filter, as sort-driver

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#31]
If the last argument of a ViewPort is a named listing report, then the "report.name.sort=" line is used to drive the sort-order of the ViewPort. This does not use any other aspect of the defined report, and does not affect the metadata that Taskwiki displays.
<pre>
=== FooBar tasks | project:foo +bar ls | project:foo ===
</pre>
will use the report.ls.sort= definition, to determine the order that tasks are displayed. This obviously would apply only to those reports that generate task lists (list, ls, long, minimal etc.) unlike summary or graphic reports (ghistory, summary etc) which would be ignored.

**Comment by tbabej** [comment]
So the new way do define sort orders would be:

    === FooBar tasks | project:foo +bar | project:foo $T ===

where you sort order 'T' in your .vimrc:

    taskwiki_sort_orders = {'T':'due+,scheduled-'}

We could link this with report orders defined in .taskrc, however, not sure if that's a feature anybody would need.

Thoughts?

**Comment by tbabej** [comment]
It could then look like this:

    taskwiki_sort_orders = {'T':'<list>'}

**Comment by tbabej** [comment]
I am going to decline the extension to source order definitions from TW directly..Reason is that:TW uses much finer grained attributes to sort (such as urgency, entry, etc.) to have a stable sorting order, while in taskwiki, user might want to reorder tasks manually.

If we used thse fine-grained attributes, manual reorders would be always reset. Hence users must define sort orders only for those attributes that are supposed to override the manual ordering in the taskwiki file - which means shorter list of attributes than TW uses.

**Comment by linuxcaffe** [comment]
Your implementation is a much better solution, thanks!
