### ISSUE TITLE
Tasks generated by the viewport should respect the dependency order

### ISSUE THREAD

**Issue by tbabej** [tbabej/taskwiki#32]
Taskwiki uses indentation to denote dependencies, however, tasks generated by the viewport are simply added at the base level of indentation.

**Comment by linuxcaffe** [comment]
Vimwiki uses indentation to denote dependencies, but does taskwiki?
Having dependencies indented below parent-tasks, in a ViewPort, would be awesome, 
almost as awesome as being able to set/ change dependencies by ">>" or "<<" changing indentation.

**Comment by tbabej** [comment]
Dependencies are being added (indented task is blocking it's direct parent), otherwise my first comment would make little sense :) That said, unindentation will not make dependency go away, to avoid removing some other, irrelevant, dependencies.

**Comment by linuxcaffe** [comment]
maybe (thinking out loud) if more that one dep is affected by indenting or outdenting, a dialog could ask <pre>
There are 3 dependencies affected: change dependency of 142, 31, 82?
</pre>

**Comment by tbabej** [comment]
ViewPorts now generate tasks while respecting the dependency order (and indent properly).
