### ISSUE TITLE
Add syntax highlighting for low/medium/high priority tasks

### ISSUE THREAD

**Issue by tbabej** [tbabej/taskwiki#39]
The description should be highlighted in color.

**Comment by linuxcaffe** [comment]
I agree that priority hilighting is a good thing. 
I like H=bold white, L=gray, M & none get no specific hilight.
have a peek at my personal themes, if you dare: https://github.com/linuxcaffe/themes
I like 'em much better than the defaults.

**Comment by tbabej** [comment]
Personal preferences are irrelevant - the colors need to be customizable.

**Comment by linuxcaffe** [comment]
agreed

**Comment by tbabej** [comment]
It's not a bad idea - I like it. It actually seems I can do this in a efficient way. Stay tunes.

**Comment by tbabej** [comment]
Implemented in master.
