### ISSUE TITLE
:TWWShowTaskInfo command

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#4]
This command opens a new split window with the full task info, like the 'task info' command, or even more the vim-taskwarrior TaskInfo command.

**Comment by linuxcaffe** [comment]
recent upgrades to vim-taskwarrior now offer the command :TWReportInfo < ID|uuid >. Invoking it pops up a window-split with fill task information displayed. Hit < CR > or "q" to close the split. 

This could suggest a use of vim-taskwarrior as a companion app or as example code, but I believe it to be an ideal behavior on hitting < CR > over a [[ID|uuid]] link.

**Comment by tbabej** [comment]
If this is already implemented in vim-taskwarrior, we might as well pull that part of the plugin in taskwiki as well, licences are compatible.

**Comment by tbabej** [comment]
Implemented as ```:TaskWikiInfo``` command.
