### ISSUE TITLE
warning: "New task $DESCRIPTION may not match ViewPort filter, hit ENTER to continue"

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#47]
A ViewPort will assign any (simple) attributes in the filter, to any new tasks created under it. That way new tasks won't simply disappear as soon as they are added. If you want to define what attributes are added, you can do so after the second "|", like this;
<pre>
== ViewPort Title | project:foo +bar | +bazz ==
</pre>
and this will add "project:foo +bar +bazz" to any new tasks. 

But it's easy to define a valid ViewPort filter, with or without added defaults, 
<pre>
== Most Urgent Tasks | +PENDING urgency.over:20 ==
</pre>
where the new task may or may not match the filter, and it may or may not disappear as soon as it's saved. This is OK, and should be allowed, but it might be mitigating (less disturbing) if a warning message were generated, when a new task is about to be saved, under a ViewPort with no discernible default in the filter.

**Comment by linuxcaffe** [comment]
thinking about it, this dialog may be unnecessary

**Comment by tbabej** [comment]
The main issue here is that we are not interacting with the buffer at the point when the tasks are written down - we are interacting when the file is saved, so the warning is somewhat delayed.

I am not opposed to requiring confirmation in such cases, if optional and somebody wants it.
