### ISSUE TITLE
message: (no matches)

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#48]
What's the visual difference between a ViewPort where the filter has no matches, and a regular vimwiki heading? The answer is: none. A ViewPort _with_ matches at least has a group of tasks below it.

A viewPort could still be useful with "no matches", but there should be some indication, and it shouldn't take up any extra lines, so I suggest:
<pre>
== Booze Business Tasks | +bizz +buz +booze ==
</pre>
might resolve to:
<pre>
== Booze Business Tasks == (no matches)
</pre>
in normal mode

**Comment by tbabej** [comment]
I think it's usually kind of obvious that this particular heading is a ViewPort (see usage of "Tasks" in your own example).

Furthermore, we don't do any redrawing of the ViewPort definition currently.

Closing for now, I will accept a PR though, if it comes with docs & tests.
