### ISSUE TITLE
:TaskWikiGrid use vim-taskwarrior, if available

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#49]
The TaskWikiGrid looks almost exactly like a vim-taskwarrior report, but doesn't act like it, vim-tw has a slew of features, and mappings, that I wouldn't expect TaskWiki to re-implement. 

So I would suggest that TaskWikiGrid implement a simplified grid _unless_ vim-taskwarrior is found to be installed, in which case, the command should pass the job off to vim-tw.

**Comment by tbabej** [comment]
I'm not sure I follow, ```TaskWikiGrid``` is vim-taskwarrior. There is no plans to support it without vim-taskwarrior.

**Comment by linuxcaffe** [comment]
oh.. cool..
