### ISSUE TITLE
Tasklist generation by headings with custom VimwikiLinkHandler

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#5]
This is a custom vimwiki scheme (see :help vimwiki 5.12. Schemes and VimwikiLinkHandler) that can be used to generate a task list.

The main idea is to provide a link, that causes a list to be generated, showing ALL tasks that match the < filter >. This way, a user could create a heading;

== [[task: proj:tw +bug|Taskwarrior Project Bugs]] ==

and then can be confident that every task matching the filter would be inserted below the heading, in taskwiki format. Changes and additions are then propagated to and from taskwarrior.

**Comment by linuxcaffe** [comment]
This is very much like teranex's :InsertTasks < filter > but closer to core vimwiki functionality. It would form the backbone of a task-dashboard, and vimwiki-diary entries and more.

**Comment by tbabej** [comment]
I will need to investigate the link handlers. Otherwise sounds like a sound proposal.

**Comment by tbabej** [comment]
Implemented by ViewPorts.
