### ISSUE TITLE
new command: TaskWikiSort \<field(s)\>

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#50]
This command would sort a ViewPort or visually-selected group of tasks, using the \<field(s)\> argument, perhaps emulating a report.foo.sort= config syntax.
If no arguments provided, the command should sort on description(?).

**Comment by tbabej** [comment]
Note: New tasks inserted in the viewport now implicitly sorted on the 'entry' attribute.

**Comment by tbabej** [comment]
Implemented in master.
