### ISSUE TITLE
:TaskWikiInspect should show "Defaults for new tasks: "

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#52]
Showing whatever combination of filter and user-defaults, that will be added to new tasks, would be valuable info for Inspect

**Comment by linuxcaffe** [comment]
Actually, repeating the Title-part of the VP, in the TaskWikiInspect window, would also be helpful because, with that window open, there's no direct visual clue as to which VP is being inspected.
<pre>
ViewPort inspection:
--------------------
Title: test Project Madoc
Filter used: -DELETED +PENDING project:madoc
Defaults for new tasks: project:madoc area:home pri:L
Matching taskwarrior tasks: 3
Displayed tasks: 3
Tasks to be added:
Tasks to be deleted:
</pre>

**Comment by tbabej** [comment]
Fixed in master.
