### ISSUE TITLE
Integrate (itchyny's) calendar.vim

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#53]
This is not to be confused with with the venerable calendar-vim by Matsumoto, or the fresher calendar-vim by Mattn, Itchyny's calendar-vim is a brilliant project that offers truly useful Day, Days, Week, Month and year views. see : https://github.com/itchyny/calendar.vim

 Integrating this calendar would be the first time ever that taskwarrior tasks land on a real-live calendar.

Difficulty: unknown
Importance: life-changing

I'm not sure about the mechanics of this project, the EVENT data is stored, but it seems delightfully usable and very well documented,

I _am_ sure that having tasks displayed in a proper calendar (month, week, days, and day view) will have a profound impact on my workflow and general state of calendaric confusion. It's a big RFE, but not frivolously filed, thanks for considering it.

**Comment by tbabej** [comment]
I am not sure how you propose the integration. Additionally, it needs to be worked out what are the possible integration points (how to provide the list of tasks to the calendar.vim) with its developers.

**Comment by linuxcaffe** [comment]
I'm not sure either, integration points DO need to be worked out, I will contact the developer, see if he can provide clues.

**Comment by linuxcaffe** [comment]
TaskWikiCalendar should still invoke 'task calendar', but maybe different views could be called with 
TaskWikiDay
TaskWikiDays
TaskWikiWeek
TaskWikiMonth

**Comment by linuxcaffe** [comment]
The calendar.vim developer, ichyny, gracefully declined to add taskwiki support directly, but shared some helpful information:

"The downloaded items are kept in ~/.cache/calendar.vim/. The app calendar.vim just saves the response of Google Calendar API, thus the format is just as you see in its reference https://developers.google.com/google-apps/calendar/v3/reference/. "

**Comment by tbabej** [comment]
So somebody might make an export into that (peculiar) format, and keep syncing changes back, after ```Calendar``` completes, it would be hackish and way too much work.

More proper way would be to implement new backend for Calendar.vim, but that still requires too much work, around the level of implementing new taskwiki.

**Comment by linuxcaffe** [comment]
One possible "back end", or at least source of inspiration, might be Gary Bennett's gtasks_export.pl (https://github.com/garybgenett/tasks/blob/master/scripts/gtasks_export.pl). The script converts task data to Gtask data for a one-way-ride; task --> googletask. This might (or might not) be helpful in populating ~/cache/calendar.vim.local/event files, It's certainly not a complete solution, but it's on the path.

Google Task syncing might also be an "end-run" around the problem; sync with Gtasks, by whatever means, then use calendar.vim's native Gtask syncing, and voila!

**Comment by linuxcaffe** [comment]
Another avenue (just to list it here) might be mattn's googletasks-vim
  (https://github.com/mattn/googletasks-vim) not taskwarrior-specific, but extends Gtasks to vim.
