### ISSUE TITLE
un-conceal dis-abled ViewPort headers

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#55]
The following lines are (deliberately) dis-abled with the leading characters:
<pre>
%NUL%== Tasks Due Today | due:%date% ==
%NUL%== Tasks Completed Today | end:%date% | status:completed ==
</pre>
but due to concealment, and because they no longer generate a list, only the following is seen
(except when in insert-mode, with cursor on the line) syntax highlighng turned off:
<pre>
%NUL%== Tasks Due Today ==
%NUL%== Tasks Completed Today  ==
</pre>
and it would be better, in this template use-case, with the headers dis-abled, _not_ to conceal anything.

**Comment by tbabej** [comment]
Not doable, we would have to change ```VimwikiHeader``` definition to something else, and it's vimwiki where that's defined.

So the proper place to fix this is to change vimwiki to allow only whitespace preceding the header definition on the same line so that:

    <whitespace> == Header ==

is allowed, but

    %NUL% == Header ==

is not.

**Comment by linuxcaffe** [comment]
What about using some other aspect of a ../templates/template.bla.wiki file to dis-associate with vimwiki and taskwiki, altogether??

**Comment by tbabej** [comment]
Not sure I follow. Can you elaborate?

**Comment by linuxcaffe** [comment]
I'm thinking of a command that disables vimwiki/ taskwiki entirely, like changing the filetype to txt

**Comment by tbabej** [comment]
Well, the command is:

    set filetype=whateverbutnotvimwiki
