### ISSUE TITLE
make deleted tasks visually apparent

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#56]
It's possible to have a viewport display deleted tasks, but there's no way to visually differentiate between a deleted task and a pending one!

Like completed and active tasks, deleted tasks should be displayed as clearly different. Maybe:
<pre>
- [#] This task was deleted
</pre> 
or
<pre>
- [/] This task was deleted
</pre> 
(this is extra important, as I have been seeing deleted tasks in viewports with -DELETED v-tag (bug!))

**Comment by tbabej** [comment]
Fixed in master.

Btw, you must have used 'or' in your filters for that to happen.
