### ISSUE TITLE
new command: TaskWikiAdd

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#57]
Yes, it's easy to add a new task like
<pre>
* [ ] This is a new task
</pre>
but that doesn't make it any easier to enter (or even remember) values for all of the available attributes.

Using vimform_vim (https://github.com/tomtom/vimform_vim, yet another handy vim plugin) or something like it. the TaskWikiAdd (or < leader >ta) command would open a window-split with all modifiable attributes displayed, ready to be quickly entered. Something like this (which shows a couple of UDAs): 
<pre>
      Add New Task
========================
    Description:
        Project:
           Tags:
       Priority: (single choice/drop-down list)
        Depends:
          Recur: (single choice/drop-down list)
       Due date:
      Wait date:
 Scheduled date:
     Until date:
           Area:
          Phase:
        Started: [ ]
      Completed: [ ]
========================
 [ Submit ] [ Cancel ]
</pre>
vimform_vim supports text-fields, checkboxes and single choice/drop-down lists.
If invoked from within a ViewPort, VP defaults could be pre-populated in the form.

(TaskWikiAnnotate would get re-mapped to < leader >tA)

**Comment by linuxcaffe** [comment]
This could also be invoked for TaskWikiEdit (< leader >e) pre-populated with all attributes, leaving TaskWikiEditFile (< leader >E) as the "edit" behavior we have now.

**Comment by tbabej** [comment]
So you can achieve something similiar just by saving the file and then calling ```:TaskWikiEdit```.

Do I gather correctly that the improvement here is in the form usage (i.e. completion for values) itself?

**Comment by linuxcaffe** [comment]
The primary improvement would be
a) visibility of all modifiable attribute 
b) pre-population of attributes, using ViewPort defaults
c) input constrained by single choice/drop-downs and checkboxes
d) speedier input, no need to enter the attribute-names

**Comment by tbabej** [comment]
The improvements a), b), and d) are available with the saving and calling ```:TaskWikiEdit```.

**Comment by linuxcaffe** [comment]
a) the form in _much_ clearer, no extraneous metadata, or explanations, no blank lines and none of the many unmodifiable fields.
b) the form for TaskWikiAdd (which is the primary issue here) prepopulated with ViewPort defaults (if any) is very different from an Edit Page. and is not cogent to Add function.
c) navigating a form would be _way_ faster than editing the data in an Edit page, navigating to the line and the word in the line, and the Edit page comes with warnings and has _many_ opportunities to screw up, hit an "endless loop", modify something unmodifiable, or add a line, or..  conversely, the form has constrained navigation and available data constraints.. it ain't the same thing. 

This is primarily about TaskWikiAdd, and TaskWikiEdit was really just a piggy-back, value-add idea (and a good one :-). 

Try the form out, it's really quite charming, and the non-uber-geek audience would really appreciate it.

**Comment by tbabej** [comment]
Having to fill in a form to enter a task into taskwiki beats the purpose of keeping the tasks in this simplistic format in my opinion.

I open to enhancements, however, if they come with proper tests and docs :)
