### ISSUE TITLE
config: g:taskwiki_use_tagbar=1

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#58]
With this setting, Tagbar will always be used when a taskwiki is opened.
(there may be some other way to do this, but..)

I'll lump in
<pre>
g:taskwiki_use_nerdtree=1
</pre>
in this same issue, because the function is so similar.

**Comment by tbabej** [comment]
There should be ```tagbar``` and ```nerdtree``` related options - please read their docs.
