### ISSUE TITLE
new command: TaskWikiNote

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#59]
Similar to tasknote (of which there are several versions) TaskWikiNote (< leader >tn) opens a note in the designated directory (maybe defaulting to ~/.task/notes/, but configurable). 
Important differences, from other tasknotes implementations, might be a better, more descriptive filename, like **task-833ca489.note.txt** and that tasknote file extension (and therefore the filetype) should be user-configurable.

g:taskwiki_note_dir = ~/.task/notes
and
g:taskwiki_note_ext = note.txt

**Comment by tbabej** [comment]
I'm not using tasknote right now, I prefer to keep my notes related to tasks just right in the taskwiki file.

This sounds like a simple enhancement for somebody to implement. I'm cleaning this out of my backlog, however, will accept a PR in the future.
