### ISSUE TITLE
Default values for any attribute in given tasklist

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#6]
Like the Default Values in teranex's vimwiki-tasks, if the first ten linkes of a wiki-file have 

%% Project: <projectname>
or
%% Tags: +tag1 +tag2

then these values are added to each new project on that wiki page.

**Comment by linuxcaffe** [comment]
Yeah, I agree that < 10 lines is arbitrary, and the "%%Project" is kinda ugly.
Imho, it would be better if project and/or tag defaults could be "turned on and off" at any pont in a wiki file, affecting on-add for all tasks below it, Change any project or tag at any point, and discontinue the defaults with a blank value. like;

project: vim-tw

task, task, task (gets project: vim-tw)

tag: buz

task, task, task (gets project: vim-tw +buz)

project: twwiki

task, task, task (gets project: twwiki +buz)

project:
tag:

task, task, task (no defaults)

**Comment by linuxcaffe** [comment]
a different approach;

If the attribute on-add defaults were more header centric then perhaps the "switches coule be the trailing part of a header line, so that;

      === [[Proj Foo High Urgency|task: project:foo urgency.over:20 +urgent]]===     project foo :urgent:

This might seem redundant, but the link part defines the list, and the trailing part the on-add defaults. 

This would play nicely with #5

**Comment by tbabej** [comment]
Let's keep this issue simple - adding default values for other attributes than ```Project```. Since attributes might be arbitrary (UDAs), we will indeed need to introduce some syntax.

As for the header-centric defaults, I think using

```
=== [[Proj Foo High Urgency|task: project:foo urgency.over:20 +urgent]]===
```

should imply that any task created under this heading has set ```Project: foo``` , ```urgency``` being ignored as it is read-only attribute.

But this is a separate issue, let's not crowd it here.

**Comment by tbabej** [comment]
Implemented with ViewPorts.
