### ISSUE TITLE
hilight selected line when reports have focus or prompts are active

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#60]
currently, if I invoke a report (info, for example) or a prompt (Enter modifications: , for example) the primary window loses focus and the cursor disappears, and this is normal, BUT while those reports or prompts are active, it would be _really_ helpful to be able to confirm which line, or ViewPort the report or prompt is related to.

Because the actions are mostly line-based, or ViewPort-related, hilighting the whole line that the cursor was (is) on, when that window loses focus, would be ideal.

**Comment by tbabej** [comment]
Fixed in master.
