### ISSUE TITLE
"T" should toggle task status

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#62]
Vimwiki has the keymap "T" toggle the checkboxes of Todos. This actually works half-way with taskwiki; todos (tasks) can be marked completed with "T", and on saving, that task is correctly status:completed, HOWEVER, if you hit "T" again, the checkbox will be cleared, the task appears to be "pending" again, but on saving, that task does NOT get reverted to status:pending, just looks that way.

**Comment by tbabej** [comment]
Fixed in master.
