### ISSUE TITLE
config: g:taskwiki_active=1  -- the "off" switch

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#63]
In experimentation, to see the impact of taskwiki on vimwiki features, it would be handy if a single configuration could "turn taskwiki off". 
Without the config, the default is "on", of course.

**Comment by tbabej** [comment]
Fixed in master, however, it's just a question of existence of this variable. Any value will turn taskwiki off. It's called ```g:taskwiki_disable```.
