### ISSUE TITLE
bug: taskwiki hides tables and loses :tag: hilighting in tasks

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#64]
Taskwiki's color rules have knocked of a couple of vimwiki hilights.
The tables are invisible, with taskwiki active, and :tags: in tasks are no longer hilighted. 

![taskwiki-vimwiki test wiki-screenshot](https://cloud.githubusercontent.com/assets/2353531/7219084/309302e2-e65d-11e4-8b9f-73bda68a8c64.gif)

**Comment by linuxcaffe** [comment]
bold formatting is also slightly molested, when used in a valid task, 
and even slightly weirder than the :tag: dysfunction, 
the asterisks are not translated to the taskwarrior data version
<pre>
* [ ] show :tag: and *bold* in tasks  
</pre>

**Comment by tbabej** [comment]
What exactly does happen between those two screenshots? Taskwiki is enabled/disabled?

**Comment by linuxcaffe** [comment]
yes

**Comment by linuxcaffe** [comment]
I should have noted that this is with the "tags" branch of vimwiki, which hasn't yet been merged into master.

**Comment by tbabej** [comment]
Does the table disappear completely or is it just concealed?

**Comment by linuxcaffe** [comment]
just concealed

**Comment by tbabej** [comment]
Concealement of the tables should be fixed.

**Comment by linuxcaffe** [comment]
tables are revealed!

**Comment by linuxcaffe** [comment]
opened related issue #87
