### ISSUE TITLE
New header type - default inherited filter

### ISSUE THREAD

**Issue by tbabej** [tbabej/taskwiki#69]
Currently, one has to repeat himself a lot in one taskwiki file, if it is related to a one particular area of tasks.

The proposal is to create a new kind of a header, whose filter does not serve to generate tasks, but only to be inherited into viewports that are hierarchically under it.

```
=== Taskwiki tasks | project:Taskwiki ===
(does not generate tasks)

==== Bugs | +bug ====
(lists only Taskwiki bugs)

==== Enhancements | +rfe ===
(lists only Taskwiki RFEs)
```

**Comment by tbabej** [comment]
Syntax to distinguish this new kind of a header from viewport is yet to be decided.

**Comment by linuxcaffe** [comment]
Harnessing the hierarchy like that is fantastic!

**Comment by linuxcaffe** [comment]
inheriting user-defaults, as well as filters, would be great

**Comment by linuxcaffe** [comment]
syntax idea, enclosed in "<" or "[" as in
<pre>
== Home Project |<project:home $L>|<+house> ==
?
or something like that.

**Comment by canaaerus** [comment]
I would love such a feature too. For example I could then set a project for one file that is inherited by all viewports and new tasks.

For the syntax I think we should not use any new characters. If I'm not mistaken the filter portion of a viewport must be non-empty, so we could use the following:

    === Taskwiki tasks || project:Taskwiki ===

to define a defaults-only header. Another `|| …` clause could define default defaults when the default filter rules get too complicated, just like with viewports.

Personally I would also inherit any filters and defaults from parent viewports, but that would break backward compatibility.

What do you think about this?

**Comment by tbabej** [comment]
I think this syntax could work. There is actually an implementation of this system which could serve as a inspiration for this work - in my `knowledge` project, there is a header stacking mechanism. I think most of the code could be reused, but I'm not able to dedicate the time at the moment.

**Comment by canaaerus** [comment]
What do you think about my PR?

**Comment by tbabej** [comment]
Looks like a piece of good work. Sorry for the delay, rebased on top of current master and currently running the tests.

**Comment by tbabej** [comment]
Implemented in master.
