### ISSUE TITLE
allow use of @:context as filter

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#70]
Using predefined contexts as filters would be real handy.

== Work tasks | @:work | +work ==

**Comment by tbabej** [comment]
Sounds reasonable.

**Comment by tbabej** [comment]
Implemented in master.

**Comment by tbabej** [comment]
Syntax is simply: @context, without the colon.

**Comment by newptcai** [comment]
When I tried this I got 
```
Context definition for 'routine' could not be found.
```
