### ISSUE TITLE
vimwiki link / vieport definition disambiguation

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#72]
The vimwiki link definition is not unlike a viewport definition, especially when a link is used as a heading; 

== [[source | description]] ==                vs.           == description | source ==         respectively  

and right now, ViewPortInspect is breaking (click-jacking) vimwiki-links-as-headings (bug!)

Happily,it should be an easy fix; the double-square-bracket gives it away. If it has square-brackets, it's not a viewport.

**Comment by linuxcaffe** [comment]
vimwiki transclusions
<pre>
{{first part | second part}}
</pre>
could also be confused, and should be differentiated from viewports

**Comment by linuxcaffe** [comment]
this bug is actually biting me, please fix.

**Comment by tbabej** [comment]
Fixed in master.

**Comment by linuxcaffe** [comment]
workedlikeacharm! thanks!
