### ISSUE TITLE
Inserting a task between a child and parent doesn't remove old dependency.

### ISSUE THREAD

**Issue by harleypig** [tbabej/taskwiki#76]
If you have

```
* [ ] Parent task
  * [ ] Child task
```

Then insert a new task

```
* [ ] Parent task
  * [ ] Insert a task
    * [ ] Child task
```

The child task will still be dependent on the parent, as well as the 'insert a task' task.

**Comment by linuxcaffe** [comment]
I have the same problem as @harleypig ; any complexity in dependency hierarchy (more than two layers) causes errors and can't be :w saved. I would be crafting more comprehensive dependency-chains, but these errors prevent my from doing so in a viewport.

!http://picpaste.com/taskwiki_outline-errors_Screenshot_2015-12-09_11-28-02-eYLngtxK.png!

**Comment by tbabej** [comment]
This should be fixed now.
