### ISSUE TITLE
:TaskwikiGenIndex, :TaskwikiGenProjectIndex and :TaskwikiGenTagIndex

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#77]
Perhaps based on existing vimwiki magic, like https://github.com/vimwiki/utils/blob/master/vmtree.sh, these three commands generate $TASKWIKIDIR/index.wiki, ../project/index.wiki and ../tag/index.wiki, based on corresponding files found in those directories. These would of course be configurable locations, with sane defaults.

**Comment by tbabej** [comment]
I'd wait until the community has expanded and settled on a best (or most commonly used) taskwiki layout, if that ever happens.

For myself, I don't use this kind of layout.

Maybe a tool which would let user choose from several, pre-defined layouts would be acceptable.

**Comment by linuxcaffe** [comment]
cool, well my layout probably differs from yours in that it's outside of ~/.vim/wiki/ (where I keep my other wiki) and use of index.wiki files? I'd be interested for another peek at your layout,

I'm in the process or kludging together DIY GenIndex scripts, and I'll share them if they don't eat puppies.

As to "the community" settling on any one best-practice, it'llneverhappen, and I'm still going to keep flogging my scheme, because I think it is ultimately generic, in a taskwarrior-user sort of way. I would be even better if there was another, pre-defined layout, and/or make things configurable in a way that supports more than one layout.
