### ISSUE TITLE
use g:vimwiki_listsyms for pending parent tasks

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#78]
As found in vimwiki.txt help file, under vimwiki-todo-lists, 
<pre>
Parent items should change when their child items change. If not, use
vimwiki_glr. The symbol between [ ] depends on the percentage of toggled
child items (see also g:vimwiki_listsyms):
    [ ] -- 0%
    [.] -- 1-33%
    [o] -- 34-66%
    [O] -- 67-99%
    [X] -- 100%
</pre>
this would be super-nifty and non-conflicty in taskwiki!
(* [S] could override this)

**Comment by linuxcaffe** [comment]
it's an interesting question whether a parent task is automatically "completed" when all of it's child tasks are completed.. TBD

**Comment by linuxcaffe** [comment]
(sorry 'bout the barrage Tomas, just commenting while I think of it)

If this enhancement is accepted, I can think of two configs that might be helpful;
<pre>
g:taskwiki_listsyms=1   
g:taskwiki_listsyms_childless_completed=1
</pre>
* the first activates or deactivates the use of listsyms for parent tasks.
* the second determines whether a parent task is automatically completed, when all of it's child tasks are completed. If set to "0" then completing all child tasks simply reverts the task to "* [ ] " pending.

**Comment by tbabej** [comment]
I have no personal desire. If anyone attempts implementation, care needs to be taken so that it does not override any status flag in the [ ]. This autogenerated progress flags should have the least priority.

**Comment by tbabej** [comment]
Closing the issue, but PR will be considered. Please reopen if you want to contribute this enhancement.
