### ISSUE TITLE
Displaying IDs / short uuids in front

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#8]
This issue presumes a number of things, but I thought I would express what I feel might be an optimal layout for a task, in a vimwiki. 

<pre>
== [[task: +test|test tasks]] ==
* [X] bfea17e6 continue testing twwiki                                  :test:
        * this is the first annotation
* [ ] 107 stop screwing around with taskwarrior!                        :test:
        * [ ] 108 take stats                                        :foo:test:
        * [ ] 109 test again Project thing                              :test:
                * [ ] 111 yet another test                          :test:bar:
                        * annotation for above
                        * another bullet point/ ammotation
                * [ ] 115 the last task                         :baz:test:buz:
</pre>

The heading is shown with the link "open", 
the anotations are presented as sub-list points, 
the task IDs would be hilighted as links (to uuid), the first one, completed, used [[uuid.short|uuid]]
the tags are shown with the upcoming vimwiki tags format, and right-justified, just like they would be in orgmode.

**Comment by tbabej** [comment]
I disagree with the IDs being shown out, especially by default, and in front. Instead, a command may be used to copy the ID into the clipboard.

Showing IDs can be made configurable, it should be fairly simple improvement.

**Comment by linuxcaffe** [comment]
The reason I think that the IDs should always be shown, right up front, is that is the "handle" by which most task actions are performed.  Copying the ID to the clipboard, to be pasted somewhere, to take an action, seems like extra steps, but if you've got an idea for a configuration to show them, all is well :-)

**Comment by tbabej** [comment]
Well I was just saying that don't agree with clouting the task list area with visual metadata, therefore I will require any pull requests for this feature to provide a configurable enhancement :)

**Comment by linuxcaffe** [comment]
+ $0.02 CDN, imho, visible uuid is a clutter-monster and the mother of all useless metadata :-)

**Comment by tbabej** [comment]
Sure. But unless you're editing that line, uuid is being concealed, right?

**Comment by linuxcaffe** [comment]
ok! that sounds right, thanks!

**Comment by linuxcaffe** [comment]
achievable with something like #16

**Comment by tbabej** [comment]
Thinking some more about this, displaying IDs does not make sense if they are meant to replace the UUIDs we have now. The IDs might get easily reassigned in the TW, thus rendering the tasks obsolete (and we would be unable to get a reference to the task in the old ordering).

The conclusion is that we would have to display both IDs and UUIDs on the line for IDs to be correct.

**Comment by linuxcaffe** [comment]
Agreed, Especially if some version of a TaskInfo command were available, like #4
