### ISSUE TITLE
use "[W]" for status:waiting tasks

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#80]
Waiting tasks are not seen in most tasklists, but when they are, indicating that status with "[W]" would make it nice and clear.

**Comment by tbabej** [comment]
Agreed, has been on my mind for some time.

**Comment by tbabej** [comment]
Respective syntax highlighting should be added too, with possible sourcing from TW.

**Comment by tbabej** [comment]
Fixed in master. Also note that waiting tasks have no special color highlighting in taskwarrior directly, hence no rules are sourced.
