### ISSUE TITLE
highlighting for viewport headers 

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#81]
It bugs me that there's no visual difference between a regular vimwiki header and a viewport-with-no-matches. Syntax hilighting for VP headers would fix that.

**Comment by tbabej** [comment]
I usually mark my viewport headers with names that suggest there's going to be a list of tasks.

**Comment by linuxcaffe** [comment]
So "name suggests it's probably a viewport" work for you?
I admit this is a dupe of #48, this time with color, but I thinks it's a mistake to leave them visually ambiguous.

**Comment by tbabej** [comment]
Yep, it works for me. It's not an unreasonable request though, I am open to pull requests implementing this behaviour.

**Comment by linuxcaffe** [comment]
coolio!
