### ISSUE TITLE
How to follow Back-links

### ISSUE THREAD

**Issue by absala** [tbabej/taskwiki#82]
Hi Tomas
Really appreciate the taskwiki.

A nice feature of the taskwiki are the Backlinks:
- Back-links: The command :TaskWikiLink will add an annotation to the selected task(s) with the ~/path/to/file.wiki

Is there any command to follow an already given link?

I will try to explain what I am searching for with this example:
- generate a new task on page **~/path/to/mynewtask.wiki**
  
  ```
    * [ ] My new task
  ```
- assign this task to project **myimportantproject**
  
  ```
  <leader>tm pro:myimportantproject
  ```
- create backlink
  
  ```
   <leader>tl
  ```
- open page **projectsummary** 
  
     ===Important project's tasks | +PENDING proj:myimportantproject===

This page shows all open tasks for projoct **myimportantproject**.  I now want to jump directly to the task's assigned wiki page.

Any suggestion how to do this?

Thank you,
absala

**Comment by linuxcaffe** [comment]
@absala I think the backling are "designed" so that you have a specified reference to a specific wiki, anntated in the task itself. The only existing way to open it (fo from the cli to THAT wiki) is using taskopen (https://github.com/ValiValpas/taskopen). With taskopen installed, you could do something like;
<pre>
taskopen 142
</pre>
and if the task 142 had a backlink, you would find yourself in that wiki.. in theory

**Comment by tbabej** [comment]
Why "in theory"? Is there any specific issue? (Note: not using taskopen myself).

**Comment by absala** [comment]
Sorry, do not want to use an additional plugin,  

please check this initial suggestion:

taskwiki.py:
```python
        def follow_link(self):
            for vimwikitask in self.tasks:
                print("Follow first link of task \"{0}\".".format(vimwikitask['description']))
                for annotation in vimwikitask['annotations']:
                    description = annotation["description"]
                    if ( description.startswith("wiki:")):
                        file = description[5:].strip()
                        if (util.get_absolute_filepath() != util.expand_path_user(file)):
                            print ("Opening wiki file\"{0}\".\n".format(file))
                            vim.command("edit {0}".format(file))
                        return
                break # Only one task should be followed
            print ("No link to follow.")
```

util.py:
```python
def expand_path_user(filepath):
    return os.path.expanduser(filepath)
```

taskwiki.vim
```vim
command! -range TaskWikiFollowLink :<line1>,<line2>py SelectedTasks().follow_link()
...
" Leader-related mappings. Mostly <Leader>t + <first letter of the action>
nmap <silent><buffer> <Leader>tf :TaskWikiFollowLink<CR>
....
" Mappings for visual mode.
vmap <silent><buffer> <Leader>tf :TaskWikiFollowLink<CR>


```

**Comment by tbabej** [comment]
I think there is a confusion about what backlinks are about. If you annotate a given task with a backlink, the annotation with the path to the current file will be added.

Intention was to provide a way how to open a taskwiki file corresponding to a task with a given ID from the command line. So you type:

    $ taskopen 42

and taskopen fires a vim session, opening the corresponding taskwiki file.

Now, what you are suggesting seems like you want to jump between different taskwiki files when taskwiki is opened. Is that correct? Can we formulate the use case more precisely?

**Comment by absala** [comment]
Ok, so I did not understand your intentionof the backlinks so far. I did not know on the taskopen tool yet.

But I think that the backlinks might be really useful to navigate within taskwiki. So I can quickly can jump from a summarization list on one wiki page to the task's main wikipage.

**Comment by tbabej** [comment]
Well, I think you're right. Having some use for the backlinks without the need for a third-party tool would be useful.

So in general, the next steps would be turn this into a pull request, review, provide tests and docs.

**Comment by tbabej** [comment]
This has stalled for a long time, and it's not clear how it should be turned into a new feature. If anybody has idea and is willing to work on it, let me know, and we can reopen.

**Comment by Archie-2021** [comment]
It is for a long time ago. Is there any progress on this feature? I have taskopen installed, I just want to trigger it from inside nvim (via TaskWiki). Is there any way to create a macro and bind it to a keybind? I have done it in VIT, but not sure how to do it in taskwiki since most of taskwiki commands are interactive and not easy to program via combining them via CLI.
