### ISSUE TITLE
Task data base by wiki

### ISSUE THREAD

**Issue by absala** [tbabej/taskwiki#83]
I am wondering if you can provide a convenient way to provide a default task warrior data base for each of the different wikis according to the **g:vimwiki_list**  
Reason is to separate the task databases of some wikis strictly, to not mix up the different tasks by accident.

Different task data base files are possible, details can be found in documentation **taskwiki_extra_warriors**

But to access a different database an explicit location needs to be specified.

```
    let g:taskwiki_extra_warriors={'H': {'data_location': '/home/tbabej/.habit/', 'taskrc_location': '/hom/tbabej/.habitrc'}
    ~ === Home habits | project:Home #H ===
```

Doing so, I sometimes find my self that I forget to provide the correct key and the tasks end up in the wrong database. This might be quite uncomfortable, when syncing this to an external taskd server, that automatically saves the history...

From [vimwiki-docs](https://github.com/vimwiki/vimwiki/blob/master/doc/vimwiki.txt):

```
    11.1 Registered Wiki *g:vimwiki_list* *vimwiki-register-wiki*
    One or more wikis can be registered using the |g:vimwiki_list| variable.
    Each item in |g:vimwiki_list| is a |Dictionary| that holds all customizations
    available for a distinct wiki.
    ...
    example: >
    let g:vimwiki_list = [{'path': '~/my_habits/', 'path_html': '~/habits_html/'},
    \ {'path': '~/my_work/', 'ext': '.mdox'}]
```

So my suggestion:
Is a kind of dictonary possible like e.g.

```
    let g:taskwiki_vimwiki_database_mapping = [{'data_location': '/home/absala/.habit/', 'taskrc_location': '/home/absala/.habitrc'},
    \ {'data_location': '/home/absala/.work/', 'taskrc_location': '/home/absala/.workrc'}]
```

or even combine the data base list to g:vimwiki_list

```
   let g:vimwiki_list = [{'path': '~/my_habits/', 'path_html': '~/habits_html/',taskwiki_data_location': '/home/absala/.habit/', 'taskwiki_taskrc_location': '/home/absala/.habitrc},
    \ {'path': '~/my_work/', 'ext': '.mdox', 'taskwiki_data_location': '/home/absala/.work/', 'taskwiki_taskrc_location': '/home/absala/.workrc'}]
```

Having this mapping, taskwiki might asure that  that when working in first vimwiki ( <leader>ww) we are working on database .habit and when working in second vimwiki (2 <leader> ww), we are working on database .work

**Comment by tbabej** [comment]
Understand the suggestion, it makes sense. Instead of using default taskwarrior if no explicit tag is present, we can fall back and detect if g:taskwiki_vimwiki_database_mapping is present, selecting the appropriate value according to the filename.

Would you be willing to provide the implementation?

**Comment by absala** [comment]
Hi Tomas,
thank you for your feedback. I am on implementing this according to your comment. I still need to get familiar with the test runs. I tried to follow the description in your .travis.yml file, but getting a lot of failures un my ubuntu 12.04 system. I will try this on a virtual machine with a later ubuntu soon.

**Comment by tbabej** [comment]
Well, taskwiki is being tested on "Ubuntu 12.04 LTS Server Edition 64 bit", which means it should work just fine on your machine if you follow the instructions in the .travis.yml file.

**Comment by tbabej** [comment]
The 'client' attribute is set by the IntegrationTest.start_client method. It uses vimrunner's server.start_gvim() call, so maybe you're missing a gvim package installed on your machine?

Maybe you could try playing with the vimrunner directly, and see if the simple examples in the docs work for you. See: https://github.com/andri-ch/vimrunner-python

Nevertheless, if you'll be unable to setup a test for this, don't worry, if we get the code & docs right, I can write the test.

**Comment by absala** [comment]
testsuite issue mostly solved, results getting green: finally I needed to reinstall the ubuntu english localization language pack.
Looks like some assertions require english language.

**Comment by tbabej** [comment]
Was missing gvim package the root of the issue?

**Comment by tbabej** [comment]
@absala Please reopen if PR is still coming.
