### ISSUE TITLE
unicode support

### ISSUE THREAD

**Issue by kongluoxing** [tbabej/taskwiki#85]
task description and annotations may be unicode, it's easy to support unicode, just add `# coding: utf-8` header, and add u prefix for string may contain unicode chars.

**Comment by tbabej** [comment]
Adding a Unicode support would not be indeed that hard, as underlying tasklib library is already Unicode-friendly.

Would you be willing to work on this issue, or at least write a test case?

**Comment by tbabej** [comment]
Unicode should be supported, we have some test cases for that. If you find any issues, let us know.

**Comment by whoww** [comment]
It seems, that the unicode support does not fully work.
If I delete a task by `<leader>tD` with a Unicode character it it, Taskwiki returns:

```
Traceback (most recent call last):                                                                                                                                        
  File "<string>", line 1, in <module>                                                                                                                                    
  File "/home/adrian/.vim/bundle/taskwiki/taskwiki/main.py", line 136, in delete                                                                                          
    print("Task \"{0}\" deleted.".format(vimwikitask['description']))                                                                                                     
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd6' in position 0: ordinal not in range(128)
```

Based on this [this](http://stackoverflow.com/questions/3235386/python-using-format-on-a-unicode-escaped-string) answer and my own testing, it is enough to add the following import
`from __future__ import unicode_literals` to the `main.py`.

As I am not a python expert and only checked one file, you may want to test it for yourself.
But at least for now, it solves the problem for me.

**Comment by tbabej** [comment]
I fixed the issue by marking the literals manually, since `unicode_literals` can have unwanted consequences. Fixed in master.
