### ISSUE TITLE
Saving a file containing a done subtask raises an error

### ISSUE THREAD

**Issue by bleader** [tbabej/taskwiki#93]
Both taskwiki and tasklib have been updated, and I'm using TW 2.5.0.

    == test | project: ==
    * [ ] my task
      * [ ] my subtask

*\<leader\>td* to TaskWikiDone **my subtask** gives in *:messages*:

    Error detected while processing BufWrite Auto commands for "*.wiki":        
    Traceback (most recent call last):                                          
      File "<string>", line 1, in <module>                                      
      File "/home/morel/.vim/plugged/taskwiki/taskwiki/taskwiki.py", line 58, in update_to_tw
        cache.save_tasks()                                                      
      File "/home/morel/.vim/plugged/taskwiki/taskwiki/cache.py", line 80, in save_tasks
        task.save_to_tw()                                                       
      File "/home/morel/.vim/plugged/taskwiki/taskwiki/vwtask.py", line 284, in save_to_tw
        self.task.save()                                                        
      File "/usr/local/lib/python2.7/dist-packages/tasklib/task.py", line 392, in save
        self.backend.save_task(self)                                            
      File "/usr/local/lib/python2.7/dist-packages/tasklib/backends.py", line 319, in save_task
        output = self.execute_command(args)                                     
      File "/usr/local/lib/python2.7/dist-packages/tasklib/backends.py", line 270, in execute_command
        raise TaskWarriorException(error_msg)                                   
    tasklib.backends.TaskWarriorException: Using alternate .taskrc file /home/morel/.taskrc
    Using alternate data.location /home/morel/.task                             
    Configuration override rc.bulk:0                                            
    Configuration override rc.recurrence.confirmation:no                        
    Configuration override rc.confirmation:no                                   
    Configuration override rc.context:                                          
    Configuration override rc.data.location:/home/morel/.task                   
    Configuration override rc.dependency.confirmation:no                        
    Configuration override rc.json.array:off                                    
    Could not delete a dependency on task 0 - not found.

**Comment by bleader** [comment]
Should lilkely be declared in **tasklib**

**Comment by bleader** [comment]
Is there a reason to force completed tasks to be removed from dependencies in the parent task?

Adding the check on completed status seems to work in my test, but obviously, I don't know the rest of the code well enough to know possible side effects:

            return 'depends:' + ','.join(
                [t['uuid'] for t in added] +
                ['-' + t['uuid'] for t in removed if t['status'] != 'completed']

**Comment by tbabej** [comment]
This change will prohibit users to change dependencies of a parent task after those dependencies have been completed.

What is the motivation?

**Comment by bleader** [comment]
I want to avoid the *Could not delete a dependency on task 0 - not found.* when doing *TaskWikiDone()* on a subtask then *:w* on the file.

I tried investigating the issue, but as I'm not familiar with tasklib code I fiddle a bit randomly :)

**Comment by tbabej** [comment]
I think I see the situation clearly now - you are using +PENDING (or similiar) filter in your viewports. After marking a task done, it no longer matches the filter, so it is removed. The viewport does not differentiate between "no longer matches the filter" removal and "user manually removed the line" removal, it only detects the task that was there is absent.

Therefore it fires the modification to remove the completed task from the dependency list, which in turn fires the bug in Taskwarrior that cannot handle completed tasks when assigning/removing dependencies.

**Comment by bleader** [comment]
Issue does not arise with taskwarrior >= 2.5.0, better not waste time on this.
